-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_conv2d,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=720497,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1757,HLS_SYN_LUT=1982,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (22 downto 0) := "00000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (22 downto 0) := "00000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (22 downto 0) := "00000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (22 downto 0) := "00000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (22 downto 0) := "00000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (22 downto 0) := "00000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (22 downto 0) := "00001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (22 downto 0) := "00010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (22 downto 0) := "00100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (22 downto 0) := "01000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (22 downto 0) := "10000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal kernel_in_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal kernel_in_0_ce0 : STD_LOGIC;
    signal kernel_in_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal kernel_in_1_ce0 : STD_LOGIC;
    signal kernel_in_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal kernel_in_2_ce0 : STD_LOGIC;
    signal kernel_in_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal img_size : STD_LOGIC_VECTOR (31 downto 0);
    signal window_0_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_1_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_2_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_0_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_1_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_2_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal line_buf_1_ce0 : STD_LOGIC;
    signal line_buf_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_1_ce1 : STD_LOGIC;
    signal line_buf_1_we1 : STD_LOGIC;
    signal line_buf_0_ce0 : STD_LOGIC;
    signal line_buf_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_0_ce1 : STD_LOGIC;
    signal line_buf_0_we1 : STD_LOGIC;
    signal window_0_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_1_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_2_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln46_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln77_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal and_ln74_reg_1068 : STD_LOGIC_VECTOR (0 downto 0);
    signal virt_size_fu_489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal virt_size_reg_952 : STD_LOGIC_VECTOR (31 downto 0);
    signal add13_fu_495_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add13_reg_958 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln41_fu_501_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln41_reg_965 : STD_LOGIC_VECTOR (32 downto 0);
    signal row_2_fu_522_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal row_2_reg_973 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_978 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp69_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp69_reg_983 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_reg_988 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln43_fu_566_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_reg_993 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln43_1_fu_570_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_1_reg_999 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln43_fu_579_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_reg_1007 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln46_fu_607_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln46_reg_1024 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_op109_read_state4 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal sub_ln49_fu_625_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln49_reg_1029 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buf_0_addr_reg_1037 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_1_addr_reg_1043 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln49_fu_667_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln61_fu_753_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln61_reg_1063 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal and_ln74_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal window_0_1_load_1_reg_1075 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_1_1_load_1_reg_1083 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_2_1_load_1_reg_1091 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln62_fu_798_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln62_reg_1096 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal val_fu_802_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln65_fu_828_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln65_reg_1106 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln77_fu_842_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln77_reg_1115 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state9 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal empty_25_fu_848_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_25_reg_1120 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln82_fu_866_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln82_reg_1124 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln79_fu_894_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln79_reg_1142 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_9_fu_922_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_reg_1147 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln79_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_fu_473_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_1187 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_fu_468_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal col_reg_309 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state23 : BOOLEAN;
    signal ap_block_state23_io : BOOLEAN;
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal i_reg_321 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln48_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_pixel_fu_656_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_pixel_1_reg_333 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_reg_344 : STD_LOGIC_VECTOR (1 downto 0);
    signal window_1_2_load_1_reg_355 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal window_0_2_load_1_reg_365 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_1_reg_375 : STD_LOGIC_VECTOR (1 downto 0);
    signal window_1_2_load_14_reg_387 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_0_2_load_12_reg_399 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_reg_411 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_reg_422 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_1_reg_434 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_2_reg_445 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_in_reg_457 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln82_2_fu_906_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_690_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln49_fu_673_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_fu_180 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_473_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln41_fu_513_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_528_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal notrhs_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_617_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln49_fu_613_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln56_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_1_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_2_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_fu_677_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_690_p10 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_765_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln74_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln1_fu_858_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln82_fu_854_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln92_fu_877_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln81_fu_900_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln82_1_fu_913_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_fu_922_p10 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_838 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_mux_94_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_line_buf_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        kernel_in_0_address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        kernel_in_0_ce0 : IN STD_LOGIC;
        kernel_in_0_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_1_address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        kernel_in_1_ce0 : IN STD_LOGIC;
        kernel_in_1_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_2_address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        kernel_in_2_ce0 : IN STD_LOGIC;
        kernel_in_2_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line_buf_1_U : component conv2d_line_buf_1
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_1_addr_reg_1043,
        ce0 => line_buf_1_ce0,
        q0 => line_buf_1_q0,
        address1 => line_buf_1_addr_reg_1043,
        ce1 => line_buf_1_ce1,
        we1 => line_buf_1_we1,
        d1 => select_ln65_reg_1106);

    line_buf_0_U : component conv2d_line_buf_1
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_0_addr_reg_1037,
        ce0 => line_buf_0_ce0,
        q0 => line_buf_0_q0,
        address1 => line_buf_0_addr_reg_1037,
        ce1 => line_buf_0_ce1,
        we1 => line_buf_0_we1,
        d1 => select_ln65_reg_1106);

    control_s_axi_U : component conv2d_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        kernel_in_0_address0 => kernel_in_0_address0,
        kernel_in_0_ce0 => kernel_in_0_ce0,
        kernel_in_0_q0 => kernel_in_0_q0,
        kernel_in_1_address0 => kernel_in_1_address0,
        kernel_in_1_ce0 => kernel_in_1_ce0,
        kernel_in_1_q0 => kernel_in_1_q0,
        kernel_in_2_address0 => kernel_in_2_address0,
        kernel_in_2_ce0 => kernel_in_2_ce0,
        kernel_in_2_q0 => kernel_in_2_q0,
        img_size => img_size,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    fadd_32ns_32ns_32_5_full_dsp_1_U1 : component conv2d_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => acc_2_reg_445,
        din1 => mul_reg_1187,
        ce => ap_const_logic_1,
        dout => grp_fu_468_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U2 : component conv2d_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_9_reg_1147,
        din1 => grp_fu_473_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_473_p2);

    mux_94_32_1_1_U3 : component conv2d_mux_94_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => window_0_1,
        din2 => window_0_2,
        din3 => ap_const_lv32_0,
        din4 => window_1_1,
        din5 => window_1_2,
        din6 => ap_const_lv32_0,
        din7 => window_2_1,
        din8 => window_2_2,
        din9 => tmp_fu_690_p10,
        dout => tmp_fu_690_p11);

    mux_94_32_1_1_U4 : component conv2d_mux_94_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => window_0_0,
        din1 => window_0_1_load_1_reg_1075,
        din2 => window_0_2_load_1_reg_365,
        din3 => window_1_0,
        din4 => window_1_1_load_1_reg_1083,
        din5 => window_1_2_load_1_reg_355,
        din6 => window_2_0,
        din7 => window_2_1_load_1_reg_1091,
        din8 => new_pixel_1_reg_333,
        din9 => tmp_9_fu_922_p10,
        dout => tmp_9_fu_922_p11);

    regslice_both_in_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    acc_2_reg_445_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_0))) then 
                acc_2_reg_445 <= acc_reg_422;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                acc_2_reg_445 <= grp_fu_468_p2;
            end if; 
        end if;
    end process;

    acc_reg_422_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln74_fu_781_p2))) then 
                acc_reg_422 <= ap_const_lv32_0;
            elsif (((icmp_ln79_fu_888_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                acc_reg_422 <= acc_2_reg_445;
            end if; 
        end if;
    end process;

    col_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_1))) then 
                col_reg_309 <= ap_const_lv32_0;
            elsif ((not(((ap_const_boolean_1 = ap_block_state23_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_lv1_1 = and_ln74_reg_1068)))) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                col_reg_309 <= add_ln43_reg_1007;
            end if; 
        end if;
    end process;

    i_1_reg_375_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                i_1_reg_375 <= add_ln61_reg_1063;
            elsif ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then 
                i_1_reg_375 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    i_2_reg_411_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln74_fu_781_p2))) then 
                i_2_reg_411 <= ap_const_lv2_0;
            elsif (((icmp_ln79_fu_888_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                i_2_reg_411 <= add_ln77_reg_1115;
            end if; 
        end if;
    end process;

    i_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln43_fu_574_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_321 <= ap_const_lv2_0;
            elsif (((icmp_ln48_fu_661_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_reg_321 <= add_ln46_reg_1024;
            end if; 
        end if;
    end process;

    j_1_reg_434_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_0))) then 
                j_1_reg_434 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                j_1_reg_434 <= add_ln79_reg_1142;
            end if; 
        end if;
    end process;

    j_reg_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_0))) then 
                j_reg_344 <= ap_const_lv2_0;
            elsif (((icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_reg_344 <= add_ln49_fu_667_p2;
            end if; 
        end if;
    end process;

    new_pixel_1_reg_333_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_838)) then
                if ((ap_const_lv1_0 = and_ln55_1_fu_647_p2)) then 
                    new_pixel_1_reg_333 <= ap_const_lv32_0;
                elsif ((ap_const_lv1_1 = and_ln55_1_fu_647_p2)) then 
                    new_pixel_1_reg_333 <= new_pixel_fu_656_p1;
                end if;
            end if; 
        end if;
    end process;

    p_in_reg_457_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                p_in_reg_457 <= kernel_in_2_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                p_in_reg_457 <= kernel_in_1_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                p_in_reg_457 <= kernel_in_0_q0;
            end if; 
        end if;
    end process;

    row_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                row_fu_180 <= ap_const_lv31_0;
            elsif (((icmp_ln43_fu_574_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                row_fu_180 <= row_2_reg_973;
            end if; 
        end if;
    end process;

    window_0_2_load_12_reg_399_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((trunc_ln62_fu_798_p1 = ap_const_lv1_0)) then 
                    window_0_2_load_12_reg_399 <= val_fu_802_p3;
                elsif ((trunc_ln62_fu_798_p1 = ap_const_lv1_1)) then 
                    window_0_2_load_12_reg_399 <= window_0_2_load_1_reg_365;
                end if;
            end if; 
        end if;
    end process;

    window_0_2_load_1_reg_365_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                window_0_2_load_1_reg_365 <= window_0_2_load_12_reg_399;
            elsif ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then 
                window_0_2_load_1_reg_365 <= window_0_2;
            end if; 
        end if;
    end process;

    window_1_2_load_14_reg_387_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((trunc_ln62_fu_798_p1 = ap_const_lv1_0)) then 
                    window_1_2_load_14_reg_387 <= window_1_2_load_1_reg_355;
                elsif ((trunc_ln62_fu_798_p1 = ap_const_lv1_1)) then 
                    window_1_2_load_14_reg_387 <= val_fu_802_p3;
                end if;
            end if; 
        end if;
    end process;

    window_1_2_load_1_reg_355_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                window_1_2_load_1_reg_355 <= window_1_2_load_14_reg_387;
            elsif ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then 
                window_1_2_load_1_reg_355 <= window_1_2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add13_reg_958 <= add13_fu_495_p2;
                sext_ln41_reg_965 <= sext_ln41_fu_501_p1;
                virt_size_reg_952 <= virt_size_fu_489_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln43_reg_1007 <= add_ln43_fu_579_p2;
                    zext_ln43_1_reg_999(31 downto 0) <= zext_ln43_1_fu_570_p1(31 downto 0);
                    zext_ln43_reg_993(31 downto 0) <= zext_ln43_fu_566_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                add_ln46_reg_1024 <= add_ln46_fu_607_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln61_reg_1063 <= add_ln61_fu_753_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                add_ln77_reg_1115 <= add_ln77_fu_842_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln79_reg_1142 <= add_ln79_fu_894_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_1))) then
                and_ln55_reg_988 <= and_ln55_fu_560_p2;
                cmp69_reg_983 <= cmp69_fu_544_p2;
                icmp_reg_978 <= icmp_fu_538_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                and_ln74_reg_1068 <= and_ln74_fu_781_p2;
                window_2_2 <= new_pixel_1_reg_333;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_0))) then
                empty_25_reg_1120 <= empty_25_fu_848_p2;
                sub_ln82_reg_1124 <= sub_ln82_fu_866_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then
                line_buf_0_addr_reg_1037 <= zext_ln43_reg_993(8 - 1 downto 0);
                line_buf_1_addr_reg_1043 <= zext_ln43_reg_993(8 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                mul_reg_1187 <= grp_fu_473_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                row_2_reg_973 <= row_2_fu_522_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                select_ln65_reg_1106 <= select_ln65_fu_828_p3;
                trunc_ln62_reg_1096 <= trunc_ln62_fu_798_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_0))) then
                sub_ln49_reg_1029 <= sub_ln49_fu_625_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln79_fu_888_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                tmp_9_reg_1147 <= tmp_9_fu_922_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln49_fu_673_p1 = ap_const_lv1_0) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (i_reg_321 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_0_0 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln49_fu_673_p1 = ap_const_lv1_1) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (i_reg_321 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_0_1 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln74_fu_781_p2))) then
                window_0_1_load_1_reg_1075 <= window_0_1;
                window_1_1_load_1_reg_1083 <= window_1_1;
                window_2_1_load_1_reg_1091 <= window_2_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln62_fu_798_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                window_0_2 <= val_fu_802_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln49_fu_673_p1 = ap_const_lv1_0) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (i_reg_321 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_1_0 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln49_fu_673_p1 = ap_const_lv1_1) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (i_reg_321 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_1_1 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln62_fu_798_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                window_1_2 <= val_fu_802_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((i_reg_321 = ap_const_lv2_1)) and not((i_reg_321 = ap_const_lv2_0)) and (trunc_ln49_fu_673_p1 = ap_const_lv1_0) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_2_0 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((i_reg_321 = ap_const_lv2_1)) and not((i_reg_321 = ap_const_lv2_0)) and (trunc_ln49_fu_673_p1 = ap_const_lv1_1) and (icmp_ln48_fu_661_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                window_2_1 <= tmp_fu_690_p11;
            end if;
        end if;
    end process;
    zext_ln43_reg_993(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln43_1_reg_999(32) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln46_fu_601_p2, ap_CS_fsm_state9, icmp_ln77_fu_836_p2, ap_CS_fsm_state23, and_ln74_reg_1068, ap_CS_fsm_state2, icmp_ln41_fu_517_p2, ap_CS_fsm_state3, ap_predicate_op109_read_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, and_ln74_fu_781_p2, icmp_ln61_fu_747_p2, ap_block_state9_io, empty_25_reg_1120, ap_CS_fsm_state10, icmp_ln79_fu_888_p2, ap_block_state23_io, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln48_fu_661_p2, icmp_ln43_fu_574_p2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln43_fu_574_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln48_fu_661_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln74_fu_781_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((icmp_ln61_fu_747_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = and_ln74_fu_781_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state9 => 
                if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                elsif ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((icmp_ln79_fu_888_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif ((not((empty_25_reg_1120 = ap_const_lv2_0)) and not((empty_25_reg_1120 = ap_const_lv2_1)) and (icmp_ln79_fu_888_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((icmp_ln79_fu_888_p2 = ap_const_lv1_0) and (empty_25_reg_1120 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state23 => 
                if ((not(((ap_const_boolean_1 = ap_block_state23_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_lv1_1 = and_ln74_reg_1068)))) and (ap_const_logic_1 = ap_CS_fsm_state23))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state23;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add13_fu_495_p2 <= std_logic_vector(unsigned(img_size) + unsigned(ap_const_lv32_1));
    add_ln43_fu_579_p2 <= std_logic_vector(unsigned(col_reg_309) + unsigned(ap_const_lv32_1));
    add_ln46_fu_607_p2 <= std_logic_vector(unsigned(i_reg_321) + unsigned(ap_const_lv2_1));
    add_ln49_fu_667_p2 <= std_logic_vector(unsigned(j_reg_344) + unsigned(ap_const_lv2_1));
    add_ln61_fu_753_p2 <= std_logic_vector(unsigned(i_1_reg_375) + unsigned(ap_const_lv2_1));
    add_ln77_fu_842_p2 <= std_logic_vector(unsigned(i_2_reg_411) + unsigned(ap_const_lv2_1));
    add_ln79_fu_894_p2 <= std_logic_vector(unsigned(j_1_reg_434) + unsigned(ap_const_lv2_1));
    and_ln55_1_fu_647_p2 <= (and_ln55_reg_988 and and_ln55_2_fu_641_p2);
    and_ln55_2_fu_641_p2 <= (icmp_ln56_fu_631_p2 and icmp_ln56_1_fu_637_p2);
    and_ln55_fu_560_p2 <= (notrhs_fu_555_p2 and notlhs_fu_549_p2);
    and_ln74_fu_781_p2 <= (icmp_reg_978 and icmp_ln74_fu_775_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;

    ap_ST_fsm_state23_blk_assign_proc : process(and_ln74_reg_1068, ap_block_state23_io, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state23_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_lv1_1 = and_ln74_reg_1068)))) then 
            ap_ST_fsm_state23_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state23_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_predicate_op109_read_state4, in_stream_TVALID_int_regslice)
    begin
        if (((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(icmp_ln77_fu_836_p2, ap_block_state9_io, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state23_assign_proc : process(and_ln74_reg_1068, out_stream_TREADY_int_regslice)
    begin
                ap_block_state23 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_lv1_1 = and_ln74_reg_1068));
    end process;


    ap_block_state23_io_assign_proc : process(and_ln74_reg_1068, out_stream_TREADY_int_regslice)
    begin
                ap_block_state23_io <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_lv1_1 = and_ln74_reg_1068));
    end process;


    ap_block_state4_assign_proc : process(ap_predicate_op109_read_state4, in_stream_TVALID_int_regslice)
    begin
                ap_block_state4 <= ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state9_assign_proc : process(icmp_ln77_fu_836_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state9 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1));
    end process;


    ap_block_state9_io_assign_proc : process(icmp_ln77_fu_836_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state9_io <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1));
    end process;


    ap_condition_838_assign_proc : process(ap_CS_fsm_state4, icmp_ln46_fu_601_p2, ap_predicate_op109_read_state4, in_stream_TVALID_int_regslice)
    begin
                ap_condition_838 <= (not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln41_fu_517_p2, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op109_read_state4_assign_proc : process(icmp_ln46_fu_601_p2, and_ln55_1_fu_647_p2)
    begin
                ap_predicate_op109_read_state4 <= ((ap_const_lv1_1 = and_ln55_1_fu_647_p2) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln41_fu_517_p2, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln41_fu_517_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cmp69_fu_544_p2 <= "1" when (zext_ln41_fu_513_p1 = add13_reg_958) else "0";
    empty_25_fu_848_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(i_2_reg_411));
    grp_fu_473_p1 <= p_in_reg_457;
    icmp_fu_538_p2 <= "0" when (tmp_1_fu_528_p4 = ap_const_lv30_0) else "1";
    icmp_ln41_fu_517_p2 <= "1" when (signed(zext_ln41_fu_513_p1) < signed(virt_size_reg_952)) else "0";
    icmp_ln43_fu_574_p2 <= "1" when (col_reg_309 = virt_size_reg_952) else "0";
    icmp_ln46_fu_601_p2 <= "1" when (i_reg_321 = ap_const_lv2_3) else "0";
    icmp_ln48_fu_661_p2 <= "1" when (j_reg_344 = ap_const_lv2_2) else "0";
    icmp_ln56_1_fu_637_p2 <= "1" when (signed(zext_ln43_1_reg_999) < signed(sext_ln41_reg_965)) else "0";
    icmp_ln56_fu_631_p2 <= "0" when (col_reg_309 = ap_const_lv32_0) else "1";
    icmp_ln61_fu_747_p2 <= "1" when (i_1_reg_375 = ap_const_lv2_2) else "0";
    icmp_ln65_fu_822_p2 <= "1" when (i_1_reg_375 = ap_const_lv2_0) else "0";
    icmp_ln74_fu_775_p2 <= "0" when (tmp_3_fu_765_p4 = ap_const_lv31_0) else "1";
    icmp_ln77_fu_836_p2 <= "1" when (i_2_reg_411 = ap_const_lv2_3) else "0";
    icmp_ln79_fu_888_p2 <= "1" when (j_1_reg_434 = ap_const_lv2_3) else "0";
    icmp_ln92_fu_877_p2 <= "1" when (col_reg_309 = add13_reg_958) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln46_fu_601_p2, and_ln55_1_fu_647_p2, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln55_1_fu_647_p2) and (icmp_ln46_fu_601_p2 = ap_const_lv1_1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state4, ap_predicate_op109_read_state4, in_stream_TVALID_int_regslice)
    begin
        if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_predicate_op109_read_state4 = ap_const_boolean_1))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    kernel_in_0_address0 <= zext_ln82_2_fu_906_p1(2 - 1 downto 0);

    kernel_in_0_ce0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            kernel_in_0_ce0 <= ap_const_logic_1;
        else 
            kernel_in_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kernel_in_1_address0 <= zext_ln82_2_fu_906_p1(2 - 1 downto 0);

    kernel_in_1_ce0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            kernel_in_1_ce0 <= ap_const_logic_1;
        else 
            kernel_in_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kernel_in_2_address0 <= zext_ln82_2_fu_906_p1(2 - 1 downto 0);

    kernel_in_2_ce0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            kernel_in_2_ce0 <= ap_const_logic_1;
        else 
            kernel_in_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_ce0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            line_buf_0_ce0 <= ap_const_logic_1;
        else 
            line_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_ce1_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            line_buf_0_ce1 <= ap_const_logic_1;
        else 
            line_buf_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_we1_assign_proc : process(trunc_ln62_reg_1096, ap_CS_fsm_state8)
    begin
        if (((trunc_ln62_reg_1096 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            line_buf_0_we1 <= ap_const_logic_1;
        else 
            line_buf_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_ce0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            line_buf_1_ce0 <= ap_const_logic_1;
        else 
            line_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_ce1_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            line_buf_1_ce1 <= ap_const_logic_1;
        else 
            line_buf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_we1_assign_proc : process(trunc_ln62_reg_1096, ap_CS_fsm_state8)
    begin
        if (((trunc_ln62_reg_1096 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            line_buf_1_we1 <= ap_const_logic_1;
        else 
            line_buf_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    new_pixel_fu_656_p1 <= in_stream_TDATA_int_regslice;
    notlhs_fu_549_p2 <= "0" when (row_fu_180 = ap_const_lv31_0) else "1";
    notrhs_fu_555_p2 <= "1" when (signed(zext_ln41_fu_513_p1) < signed(add13_reg_958)) else "0";

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state9, icmp_ln77_fu_836_p2, ap_CS_fsm_state23, and_ln74_reg_1068, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state23) and (ap_const_lv1_1 = and_ln74_reg_1068)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= acc_reg_422;
    out_stream_TLAST_int_regslice <= (icmp_ln92_fu_877_p2 and cmp69_reg_983);
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state9, icmp_ln77_fu_836_p2, ap_block_state9_io, out_stream_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln77_fu_836_p2 = ap_const_lv1_1))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    row_2_fu_522_p2 <= std_logic_vector(unsigned(row_fu_180) + unsigned(ap_const_lv31_1));
    select_ln49_fu_677_p3 <= 
        ap_const_lv4_2 when (trunc_ln49_fu_673_p1(0) = '1') else 
        ap_const_lv4_1;
    select_ln65_fu_828_p3 <= 
        line_buf_1_q0 when (icmp_ln65_fu_822_p2(0) = '1') else 
        new_pixel_1_reg_333;
        sext_ln41_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add13_fu_495_p2),33));

    shl_ln1_fu_858_p3 <= (i_2_reg_411 & ap_const_lv2_0);
    shl_ln_fu_617_p3 <= (i_reg_321 & ap_const_lv2_0);
    sub_ln49_fu_625_p2 <= std_logic_vector(unsigned(shl_ln_fu_617_p3) - unsigned(zext_ln49_fu_613_p1));
    sub_ln81_fu_900_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(j_1_reg_434));
    sub_ln82_fu_866_p2 <= std_logic_vector(unsigned(shl_ln1_fu_858_p3) - unsigned(zext_ln82_fu_854_p1));
    tmp_1_fu_528_p4 <= row_fu_180(30 downto 1);
    tmp_3_fu_765_p4 <= col_reg_309(31 downto 1);
    tmp_9_fu_922_p10 <= std_logic_vector(unsigned(sub_ln82_reg_1124) + unsigned(zext_ln82_1_fu_913_p1));
    tmp_fu_690_p10 <= std_logic_vector(unsigned(sub_ln49_reg_1029) + unsigned(select_ln49_fu_677_p3));
    trunc_ln49_fu_673_p1 <= j_reg_344(1 - 1 downto 0);
    trunc_ln62_fu_798_p1 <= i_1_reg_375(1 - 1 downto 0);
    val_fu_802_p3 <= 
        line_buf_1_q0 when (trunc_ln62_fu_798_p1(0) = '1') else 
        line_buf_0_q0;
    virt_size_fu_489_p2 <= std_logic_vector(unsigned(img_size) + unsigned(ap_const_lv32_2));
    zext_ln41_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_fu_180),32));
    zext_ln43_1_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_reg_309),33));
    zext_ln43_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_reg_309),64));
    zext_ln49_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_321),4));
    zext_ln82_1_fu_913_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_reg_434),4));
    zext_ln82_2_fu_906_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln81_fu_900_p2),64));
    zext_ln82_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_reg_411),4));
end behav;
