// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_conv2d,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=720497,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1757,HLS_SYN_LUT=1982,HLS_VERSION=2021_1}" *)

module conv2d (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [1:0] kernel_in_0_address0;
reg    kernel_in_0_ce0;
wire   [31:0] kernel_in_0_q0;
wire   [1:0] kernel_in_1_address0;
reg    kernel_in_1_ce0;
wire   [31:0] kernel_in_1_q0;
wire   [1:0] kernel_in_2_address0;
reg    kernel_in_2_ce0;
wire   [31:0] kernel_in_2_q0;
wire   [31:0] img_size;
reg   [31:0] window_0_2;
reg   [31:0] window_1_2;
reg   [31:0] window_2_2;
reg   [31:0] window_0_1;
reg   [31:0] window_1_1;
reg   [31:0] window_2_1;
reg    line_buf_1_ce0;
wire   [31:0] line_buf_1_q0;
reg    line_buf_1_ce1;
reg    line_buf_1_we1;
reg    line_buf_0_ce0;
wire   [31:0] line_buf_0_q0;
reg    line_buf_0_ce1;
reg    line_buf_0_we1;
reg   [31:0] window_0_0;
reg   [31:0] window_1_0;
reg   [31:0] window_2_0;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln46_fu_601_p2;
wire   [0:0] and_ln55_1_fu_647_p2;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln77_fu_836_p2;
wire    ap_CS_fsm_state23;
reg   [0:0] and_ln74_reg_1068;
wire   [31:0] virt_size_fu_489_p2;
reg   [31:0] virt_size_reg_952;
wire  signed [31:0] add13_fu_495_p2;
reg  signed [31:0] add13_reg_958;
wire  signed [32:0] sext_ln41_fu_501_p1;
reg  signed [32:0] sext_ln41_reg_965;
wire   [30:0] row_2_fu_522_p2;
reg   [30:0] row_2_reg_973;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_fu_538_p2;
reg   [0:0] icmp_reg_978;
wire   [0:0] icmp_ln41_fu_517_p2;
wire   [0:0] cmp69_fu_544_p2;
reg   [0:0] cmp69_reg_983;
wire   [0:0] and_ln55_fu_560_p2;
reg   [0:0] and_ln55_reg_988;
wire   [63:0] zext_ln43_fu_566_p1;
reg   [63:0] zext_ln43_reg_993;
wire    ap_CS_fsm_state3;
wire   [32:0] zext_ln43_1_fu_570_p1;
reg   [32:0] zext_ln43_1_reg_999;
wire   [31:0] add_ln43_fu_579_p2;
reg   [31:0] add_ln43_reg_1007;
wire   [1:0] add_ln46_fu_607_p2;
reg   [1:0] add_ln46_reg_1024;
reg    ap_predicate_op109_read_state4;
reg    ap_block_state4;
wire   [3:0] sub_ln49_fu_625_p2;
reg   [3:0] sub_ln49_reg_1029;
reg   [7:0] line_buf_0_addr_reg_1037;
reg   [7:0] line_buf_1_addr_reg_1043;
wire   [1:0] add_ln49_fu_667_p2;
wire    ap_CS_fsm_state5;
wire   [1:0] add_ln61_fu_753_p2;
reg   [1:0] add_ln61_reg_1063;
wire    ap_CS_fsm_state6;
wire   [0:0] and_ln74_fu_781_p2;
wire   [0:0] icmp_ln61_fu_747_p2;
reg   [31:0] window_0_1_load_1_reg_1075;
reg   [31:0] window_1_1_load_1_reg_1083;
reg   [31:0] window_2_1_load_1_reg_1091;
wire   [0:0] trunc_ln62_fu_798_p1;
reg   [0:0] trunc_ln62_reg_1096;
wire    ap_CS_fsm_state7;
wire   [31:0] val_fu_802_p3;
wire   [31:0] select_ln65_fu_828_p3;
reg   [31:0] select_ln65_reg_1106;
wire   [1:0] add_ln77_fu_842_p2;
reg   [1:0] add_ln77_reg_1115;
reg    ap_block_state9;
reg    ap_block_state9_io;
wire   [1:0] empty_25_fu_848_p2;
reg   [1:0] empty_25_reg_1120;
wire   [3:0] sub_ln82_fu_866_p2;
reg   [3:0] sub_ln82_reg_1124;
wire   [1:0] add_ln79_fu_894_p2;
reg   [1:0] add_ln79_reg_1142;
wire    ap_CS_fsm_state10;
wire   [31:0] tmp_9_fu_922_p11;
reg   [31:0] tmp_9_reg_1147;
wire   [0:0] icmp_ln79_fu_888_p2;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [31:0] grp_fu_473_p2;
reg   [31:0] mul_reg_1187;
wire    ap_CS_fsm_state17;
wire   [31:0] grp_fu_468_p2;
wire    ap_CS_fsm_state22;
reg   [31:0] col_reg_309;
reg    ap_block_state23;
reg    ap_block_state23_io;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [1:0] i_reg_321;
wire   [0:0] icmp_ln48_fu_661_p2;
wire   [0:0] icmp_ln43_fu_574_p2;
wire   [31:0] new_pixel_fu_656_p1;
reg   [31:0] new_pixel_1_reg_333;
reg   [1:0] j_reg_344;
reg   [31:0] window_1_2_load_1_reg_355;
wire    ap_CS_fsm_state8;
reg   [31:0] window_0_2_load_1_reg_365;
reg   [1:0] i_1_reg_375;
reg   [31:0] window_1_2_load_14_reg_387;
reg   [31:0] window_0_2_load_12_reg_399;
reg   [1:0] i_2_reg_411;
reg   [31:0] acc_reg_422;
reg   [1:0] j_1_reg_434;
reg   [31:0] acc_2_reg_445;
reg   [31:0] p_in_reg_457;
wire   [63:0] zext_ln82_2_fu_906_p1;
wire   [31:0] tmp_fu_690_p11;
wire   [0:0] trunc_ln49_fu_673_p1;
reg   [30:0] row_fu_180;
wire    ap_CS_fsm_state18;
wire   [31:0] grp_fu_473_p1;
wire   [31:0] zext_ln41_fu_513_p1;
wire   [29:0] tmp_1_fu_528_p4;
wire   [0:0] notrhs_fu_555_p2;
wire   [0:0] notlhs_fu_549_p2;
wire   [3:0] shl_ln_fu_617_p3;
wire   [3:0] zext_ln49_fu_613_p1;
wire   [0:0] icmp_ln56_fu_631_p2;
wire   [0:0] icmp_ln56_1_fu_637_p2;
wire   [0:0] and_ln55_2_fu_641_p2;
wire   [3:0] select_ln49_fu_677_p3;
wire   [3:0] tmp_fu_690_p10;
wire   [30:0] tmp_3_fu_765_p4;
wire   [0:0] icmp_ln74_fu_775_p2;
wire   [0:0] icmp_ln65_fu_822_p2;
wire   [3:0] shl_ln1_fu_858_p3;
wire   [3:0] zext_ln82_fu_854_p1;
wire   [0:0] icmp_ln92_fu_877_p2;
wire   [1:0] sub_ln81_fu_900_p2;
wire   [3:0] zext_ln82_1_fu_913_p1;
wire   [3:0] tmp_9_fu_922_p10;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
reg    ap_condition_838;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
#0 window_0_2 = 32'd0;
#0 window_1_2 = 32'd0;
#0 window_2_2 = 32'd0;
#0 window_0_1 = 32'd0;
#0 window_1_1 = 32'd0;
#0 window_2_1 = 32'd0;
#0 window_0_0 = 32'd0;
#0 window_1_0 = 32'd0;
#0 window_2_0 = 32'd0;
end

conv2d_line_buf_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_1_addr_reg_1043),
    .ce0(line_buf_1_ce0),
    .q0(line_buf_1_q0),
    .address1(line_buf_1_addr_reg_1043),
    .ce1(line_buf_1_ce1),
    .we1(line_buf_1_we1),
    .d1(select_ln65_reg_1106)
);

conv2d_line_buf_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_0_addr_reg_1037),
    .ce0(line_buf_0_ce0),
    .q0(line_buf_0_q0),
    .address1(line_buf_0_addr_reg_1037),
    .ce1(line_buf_0_ce1),
    .we1(line_buf_0_we1),
    .d1(select_ln65_reg_1106)
);

conv2d_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .kernel_in_0_address0(kernel_in_0_address0),
    .kernel_in_0_ce0(kernel_in_0_ce0),
    .kernel_in_0_q0(kernel_in_0_q0),
    .kernel_in_1_address0(kernel_in_1_address0),
    .kernel_in_1_ce0(kernel_in_1_ce0),
    .kernel_in_1_q0(kernel_in_1_q0),
    .kernel_in_2_address0(kernel_in_2_address0),
    .kernel_in_2_ce0(kernel_in_2_ce0),
    .kernel_in_2_q0(kernel_in_2_q0),
    .img_size(img_size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(acc_2_reg_445),
    .din1(mul_reg_1187),
    .ce(1'b1),
    .dout(grp_fu_468_p2)
);

conv2d_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_9_reg_1147),
    .din1(grp_fu_473_p1),
    .ce(1'b1),
    .dout(grp_fu_473_p2)
);

conv2d_mux_94_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_94_32_1_1_U3(
    .din0(32'd0),
    .din1(window_0_1),
    .din2(window_0_2),
    .din3(32'd0),
    .din4(window_1_1),
    .din5(window_1_2),
    .din6(32'd0),
    .din7(window_2_1),
    .din8(window_2_2),
    .din9(tmp_fu_690_p10),
    .dout(tmp_fu_690_p11)
);

conv2d_mux_94_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_94_32_1_1_U4(
    .din0(window_0_0),
    .din1(window_0_1_load_1_reg_1075),
    .din2(window_0_2_load_1_reg_365),
    .din3(window_1_0),
    .din4(window_1_1_load_1_reg_1083),
    .din5(window_1_2_load_1_reg_355),
    .din6(window_2_0),
    .din7(window_2_1_load_1_reg_1091),
    .din8(new_pixel_1_reg_333),
    .din9(tmp_9_fu_922_p10),
    .dout(tmp_9_fu_922_p11)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd0))) begin
        acc_2_reg_445 <= acc_reg_422;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        acc_2_reg_445 <= grp_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln74_fu_781_p2))) begin
        acc_reg_422 <= 32'd0;
    end else if (((icmp_ln79_fu_888_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_reg_422 <= acc_2_reg_445;
    end
end

always @ (posedge ap_clk) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd1))) begin
        col_reg_309 <= 32'd0;
    end else if ((~((1'b1 == ap_block_state23_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_1068))) & (1'b1 == ap_CS_fsm_state23))) begin
        col_reg_309 <= add_ln43_reg_1007;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_reg_375 <= add_ln61_reg_1063;
    end else if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
        i_1_reg_375 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln74_fu_781_p2))) begin
        i_2_reg_411 <= 2'd0;
    end else if (((icmp_ln79_fu_888_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_2_reg_411 <= add_ln77_reg_1115;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_574_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_321 <= 2'd0;
    end else if (((icmp_ln48_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_reg_321 <= add_ln46_reg_1024;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd0))) begin
        j_1_reg_434 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        j_1_reg_434 <= add_ln79_reg_1142;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd0))) begin
        j_reg_344 <= 2'd0;
    end else if (((icmp_ln48_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j_reg_344 <= add_ln49_fu_667_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'd0 == and_ln55_1_fu_647_p2)) begin
            new_pixel_1_reg_333 <= 32'd0;
        end else if ((1'd1 == and_ln55_1_fu_647_p2)) begin
            new_pixel_1_reg_333 <= new_pixel_fu_656_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_in_reg_457 <= kernel_in_2_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_in_reg_457 <= kernel_in_1_q0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        p_in_reg_457 <= kernel_in_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_fu_180 <= 31'd0;
    end else if (((icmp_ln43_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        row_fu_180 <= row_2_reg_973;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((trunc_ln62_fu_798_p1 == 1'd0)) begin
            window_0_2_load_12_reg_399 <= val_fu_802_p3;
        end else if ((trunc_ln62_fu_798_p1 == 1'd1)) begin
            window_0_2_load_12_reg_399 <= window_0_2_load_1_reg_365;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        window_0_2_load_1_reg_365 <= window_0_2_load_12_reg_399;
    end else if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
        window_0_2_load_1_reg_365 <= window_0_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((trunc_ln62_fu_798_p1 == 1'd0)) begin
            window_1_2_load_14_reg_387 <= window_1_2_load_1_reg_355;
        end else if ((trunc_ln62_fu_798_p1 == 1'd1)) begin
            window_1_2_load_14_reg_387 <= val_fu_802_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        window_1_2_load_1_reg_355 <= window_1_2_load_14_reg_387;
    end else if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
        window_1_2_load_1_reg_355 <= window_1_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add13_reg_958 <= add13_fu_495_p2;
        sext_ln41_reg_965 <= sext_ln41_fu_501_p1;
        virt_size_reg_952 <= virt_size_fu_489_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln43_reg_1007 <= add_ln43_fu_579_p2;
        zext_ln43_1_reg_999[31 : 0] <= zext_ln43_1_fu_570_p1[31 : 0];
        zext_ln43_reg_993[31 : 0] <= zext_ln43_fu_566_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln46_reg_1024 <= add_ln46_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln61_reg_1063 <= add_ln61_fu_753_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9))) begin
        add_ln77_reg_1115 <= add_ln77_fu_842_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln79_reg_1142 <= add_ln79_fu_894_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd1))) begin
        and_ln55_reg_988 <= and_ln55_fu_560_p2;
        cmp69_reg_983 <= cmp69_fu_544_p2;
        icmp_reg_978 <= icmp_fu_538_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        and_ln74_reg_1068 <= and_ln74_fu_781_p2;
        window_2_2 <= new_pixel_1_reg_333;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd0))) begin
        empty_25_reg_1120 <= empty_25_fu_848_p2;
        sub_ln82_reg_1124 <= sub_ln82_fu_866_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
        line_buf_0_addr_reg_1037 <= zext_ln43_reg_993;
        line_buf_1_addr_reg_1043 <= zext_ln43_reg_993;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        mul_reg_1187 <= grp_fu_473_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_2_reg_973 <= row_2_fu_522_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln65_reg_1106 <= select_ln65_fu_828_p3;
        trunc_ln62_reg_1096 <= trunc_ln62_fu_798_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd0))) begin
        sub_ln49_reg_1029 <= sub_ln49_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln79_fu_888_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        tmp_9_reg_1147 <= tmp_9_fu_922_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln49_fu_673_p1 == 1'd0) & (icmp_ln48_fu_661_p2 == 1'd0) & (i_reg_321 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        window_0_0 <= tmp_fu_690_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln49_fu_673_p1 == 1'd1) & (icmp_ln48_fu_661_p2 == 1'd0) & (i_reg_321 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        window_0_1 <= tmp_fu_690_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln74_fu_781_p2))) begin
        window_0_1_load_1_reg_1075 <= window_0_1;
        window_1_1_load_1_reg_1083 <= window_1_1;
        window_2_1_load_1_reg_1091 <= window_2_1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln62_fu_798_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        window_0_2 <= val_fu_802_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln49_fu_673_p1 == 1'd0) & (icmp_ln48_fu_661_p2 == 1'd0) & (i_reg_321 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_1_0 <= tmp_fu_690_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln49_fu_673_p1 == 1'd1) & (icmp_ln48_fu_661_p2 == 1'd0) & (i_reg_321 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_1_1 <= tmp_fu_690_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln62_fu_798_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        window_1_2 <= val_fu_802_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_reg_321 == 2'd1) & ~(i_reg_321 == 2'd0) & (trunc_ln49_fu_673_p1 == 1'd0) & (icmp_ln48_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        window_2_0 <= tmp_fu_690_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_reg_321 == 2'd1) & ~(i_reg_321 == 2'd0) & (trunc_ln49_fu_673_p1 == 1'd1) & (icmp_ln48_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        window_2_1 <= tmp_fu_690_p11;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state23_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_1068)))) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1)))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln55_1_fu_647_p2) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (ap_predicate_op109_read_state4 == 1'b1))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        kernel_in_0_ce0 = 1'b1;
    end else begin
        kernel_in_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        kernel_in_1_ce0 = 1'b1;
    end else begin
        kernel_in_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        kernel_in_2_ce0 = 1'b1;
    end else begin
        kernel_in_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buf_0_ce0 = 1'b1;
    end else begin
        line_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        line_buf_0_ce1 = 1'b1;
    end else begin
        line_buf_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln62_reg_1096 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        line_buf_0_we1 = 1'b1;
    end else begin
        line_buf_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buf_1_ce0 = 1'b1;
    end else begin
        line_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        line_buf_1_ce1 = 1'b1;
    end else begin
        line_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln62_reg_1096 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        line_buf_1_we1 = 1'b1;
    end else begin
        line_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state23) & (1'd1 == and_ln74_reg_1068)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd1)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd1))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln41_fu_517_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln43_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln48_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln74_fu_781_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln61_fu_747_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'd0 == and_ln74_fu_781_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state9 : begin
            if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~((1'b1 == ap_block_state9_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln77_fu_836_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln79_fu_888_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~(empty_25_reg_1120 == 2'd0) & ~(empty_25_reg_1120 == 2'd1) & (icmp_ln79_fu_888_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln79_fu_888_p2 == 1'd0) & (empty_25_reg_1120 == 2'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state23 : begin
            if ((~((1'b1 == ap_block_state23_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_1068))) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add13_fu_495_p2 = (img_size + 32'd1);

assign add_ln43_fu_579_p2 = (col_reg_309 + 32'd1);

assign add_ln46_fu_607_p2 = (i_reg_321 + 2'd1);

assign add_ln49_fu_667_p2 = (j_reg_344 + 2'd1);

assign add_ln61_fu_753_p2 = (i_1_reg_375 + 2'd1);

assign add_ln77_fu_842_p2 = (i_2_reg_411 + 2'd1);

assign add_ln79_fu_894_p2 = (j_1_reg_434 + 2'd1);

assign and_ln55_1_fu_647_p2 = (and_ln55_reg_988 & and_ln55_2_fu_641_p2);

assign and_ln55_2_fu_641_p2 = (icmp_ln56_fu_631_p2 & icmp_ln56_1_fu_637_p2);

assign and_ln55_fu_560_p2 = (notrhs_fu_555_p2 & notlhs_fu_549_p2);

assign and_ln74_fu_781_p2 = (icmp_reg_978 & icmp_ln74_fu_775_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state23 = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_1068));
end

always @ (*) begin
    ap_block_state23_io = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_1068));
end

always @ (*) begin
    ap_block_state4 = ((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state9 = ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state9_io = ((out_stream_TREADY_int_regslice == 1'b0) & (icmp_ln77_fu_836_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_838 = (~((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op109_read_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln46_fu_601_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op109_read_state4 = ((1'd1 == and_ln55_1_fu_647_p2) & (icmp_ln46_fu_601_p2 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp69_fu_544_p2 = ((zext_ln41_fu_513_p1 == add13_reg_958) ? 1'b1 : 1'b0);

assign empty_25_fu_848_p2 = ($signed(2'd2) - $signed(i_2_reg_411));

assign grp_fu_473_p1 = p_in_reg_457;

assign icmp_fu_538_p2 = ((tmp_1_fu_528_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_517_p2 = (($signed(zext_ln41_fu_513_p1) < $signed(virt_size_reg_952)) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_574_p2 = ((col_reg_309 == virt_size_reg_952) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_601_p2 = ((i_reg_321 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_661_p2 = ((j_reg_344 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln56_1_fu_637_p2 = (($signed(zext_ln43_1_reg_999) < $signed(sext_ln41_reg_965)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_631_p2 = ((col_reg_309 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_747_p2 = ((i_1_reg_375 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_822_p2 = ((i_1_reg_375 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_775_p2 = ((tmp_3_fu_765_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_836_p2 = ((i_2_reg_411 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_888_p2 = ((j_1_reg_434 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_877_p2 = ((col_reg_309 == add13_reg_958) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign kernel_in_0_address0 = zext_ln82_2_fu_906_p1;

assign kernel_in_1_address0 = zext_ln82_2_fu_906_p1;

assign kernel_in_2_address0 = zext_ln82_2_fu_906_p1;

assign new_pixel_fu_656_p1 = in_stream_TDATA_int_regslice;

assign notlhs_fu_549_p2 = ((row_fu_180 != 31'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_555_p2 = (($signed(zext_ln41_fu_513_p1) < $signed(add13_reg_958)) ? 1'b1 : 1'b0);

assign out_stream_TDATA_int_regslice = acc_reg_422;

assign out_stream_TLAST_int_regslice = (icmp_ln92_fu_877_p2 & cmp69_reg_983);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign row_2_fu_522_p2 = (row_fu_180 + 31'd1);

assign select_ln49_fu_677_p3 = ((trunc_ln49_fu_673_p1[0:0] == 1'b1) ? 4'd2 : 4'd1);

assign select_ln65_fu_828_p3 = ((icmp_ln65_fu_822_p2[0:0] == 1'b1) ? line_buf_1_q0 : new_pixel_1_reg_333);

assign sext_ln41_fu_501_p1 = add13_fu_495_p2;

assign shl_ln1_fu_858_p3 = {{i_2_reg_411}, {2'd0}};

assign shl_ln_fu_617_p3 = {{i_reg_321}, {2'd0}};

assign sub_ln49_fu_625_p2 = (shl_ln_fu_617_p3 - zext_ln49_fu_613_p1);

assign sub_ln81_fu_900_p2 = ($signed(2'd2) - $signed(j_1_reg_434));

assign sub_ln82_fu_866_p2 = (shl_ln1_fu_858_p3 - zext_ln82_fu_854_p1);

assign tmp_1_fu_528_p4 = {{row_fu_180[30:1]}};

assign tmp_3_fu_765_p4 = {{col_reg_309[31:1]}};

assign tmp_9_fu_922_p10 = (sub_ln82_reg_1124 + zext_ln82_1_fu_913_p1);

assign tmp_fu_690_p10 = (sub_ln49_reg_1029 + select_ln49_fu_677_p3);

assign trunc_ln49_fu_673_p1 = j_reg_344[0:0];

assign trunc_ln62_fu_798_p1 = i_1_reg_375[0:0];

assign val_fu_802_p3 = ((trunc_ln62_fu_798_p1[0:0] == 1'b1) ? line_buf_1_q0 : line_buf_0_q0);

assign virt_size_fu_489_p2 = (img_size + 32'd2);

assign zext_ln41_fu_513_p1 = row_fu_180;

assign zext_ln43_1_fu_570_p1 = col_reg_309;

assign zext_ln43_fu_566_p1 = col_reg_309;

assign zext_ln49_fu_613_p1 = i_reg_321;

assign zext_ln82_1_fu_913_p1 = j_1_reg_434;

assign zext_ln82_2_fu_906_p1 = sub_ln81_fu_900_p2;

assign zext_ln82_fu_854_p1 = i_2_reg_411;

always @ (posedge ap_clk) begin
    zext_ln43_reg_993[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln43_1_reg_999[32] <= 1'b0;
end

endmodule //conv2d
