-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_conv2d,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=250.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=239.745000,HLS_SYN_LAT=9611,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1821,HLS_SYN_LUT=7833,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal kernel_in_0_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_0_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_0_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_1_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_1_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_1_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_2_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_2_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_in_2_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal img_size : STD_LOGIC_VECTOR (31 downto 0);
    signal window_0_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_1_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_2_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal line_buf_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_0_ce0 : STD_LOGIC;
    signal line_buf_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_0_ce1 : STD_LOGIC;
    signal line_buf_0_we1 : STD_LOGIC;
    signal window_0_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal line_buf_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_1_ce1 : STD_LOGIC;
    signal line_buf_1_we1 : STD_LOGIC;
    signal line_buf_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_1_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal window_2_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln41_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal and_ln74_reg_1000 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_reg_1000_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal and_ln74_reg_1000_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal new_pixel_1_reg_341 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_pixel_1_reg_341_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op124_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal new_pixel_1_reg_341_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal new_pixel_1_reg_341_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal virt_size_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal virt_size_reg_916 : STD_LOGIC_VECTOR (31 downto 0);
    signal add13_fu_443_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add13_reg_921 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_461_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_reg_931 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_24_fu_465_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_24_reg_936 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_25_fu_469_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_25_reg_941 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_26_fu_473_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_26_reg_946 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_27_fu_477_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_27_reg_951 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_28_fu_481_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_28_reg_956 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_29_fu_485_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_29_reg_961 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_30_fu_489_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_30_reg_966 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_31_fu_493_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_31_reg_971 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_501_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_976 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln41_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_981_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_981_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_981_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buf_0_addr_reg_989 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln74_fu_754_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_reg_1000_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_reg_1000_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_reg_1000_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_1004 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_1004_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_1004_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_1004_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_1004_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buf_1_load_reg_1009 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal acc_1_0_1_fu_358_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_0_1_reg_1015 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_0_2_fu_404_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_0_2_reg_1020 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_1_fu_367_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_1_reg_1025 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_1_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_1_reg_1030 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_2_fu_418_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_2_reg_1035 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_1_2_fu_376_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_1_2_reg_1040 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_2_1_fu_385_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_2_1_reg_1045 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_2_fu_432_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_2_reg_1050 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_phi_mux_new_pixel_1_phi_fu_344_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_pixel_fu_733_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_new_pixel_1_reg_341 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln43_fu_700_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_fu_174 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln43_fu_771_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal window_load_1_2_0_fu_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_1_1_0_fu_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_1_0_0_fu_186 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_fu_190 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln41_4_fu_692_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_194 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln41_fu_602_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal mul_fu_394_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_0_1_fu_399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_0_2_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_fu_409_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_1_1_fu_372_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_fu_422_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_2_fu_381_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_1_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_501_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cast_fu_497_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_501_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_550_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln41_1_fu_546_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal notrhs_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln43_1_fu_588_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln41_1_fu_608_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln43_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_626_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp19_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln41_fu_614_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cmp69_mid1_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp69_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notrhs_mid1_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_mid1_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_3_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_fu_618_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln41_2_fu_688_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln56_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_1_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_2_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_3_fu_680_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_738_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln41_1_fu_642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_2_fu_655_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_1_2_2_fu_390_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_309 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_fadd_32ns_32ns_32_1_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_fmul_32ns_32ns_32_1_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component conv2d_line_buf_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_line_buf_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        kernel_in_0_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_0_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_0_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_1_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_1_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_1_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_2_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_2_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_in_2_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line_buf_0_U : component conv2d_line_buf_0
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_0_address0,
        ce0 => line_buf_0_ce0,
        q0 => line_buf_0_q0,
        address1 => line_buf_0_addr_reg_989,
        ce1 => line_buf_0_ce1,
        we1 => line_buf_0_we1,
        d1 => line_buf_1_q1);

    line_buf_1_U : component conv2d_line_buf_1
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address1 => line_buf_1_address1,
        ce1 => line_buf_1_ce1,
        we1 => line_buf_1_we1,
        d1 => ap_phi_mux_new_pixel_1_phi_fu_344_p4,
        q1 => line_buf_1_q1);

    control_s_axi_U : component conv2d_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        kernel_in_0_0 => kernel_in_0_0,
        kernel_in_0_1 => kernel_in_0_1,
        kernel_in_0_2 => kernel_in_0_2,
        kernel_in_1_0 => kernel_in_1_0,
        kernel_in_1_1 => kernel_in_1_1,
        kernel_in_1_2 => kernel_in_1_2,
        kernel_in_2_0 => kernel_in_2_0,
        kernel_in_2_1 => kernel_in_2_1,
        kernel_in_2_2 => kernel_in_2_2,
        img_size => img_size,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    fadd_32ns_32ns_32_1_full_dsp_1_U1 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_fu_394_p2,
        din1 => ap_const_lv32_0,
        dout => acc_1_fu_353_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U2 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_fu_353_p2,
        din1 => mul_0_1_fu_399_p2,
        dout => acc_1_0_1_fu_358_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U3 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_0_1_reg_1015,
        din1 => mul_0_2_reg_1020,
        dout => acc_1_0_2_fu_363_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U4 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_0_2_fu_363_p2,
        din1 => mul_1_fu_409_p2,
        dout => acc_1_1_fu_367_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U5 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_1_reg_1025,
        din1 => mul_1_1_reg_1030,
        dout => acc_1_1_1_fu_372_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U6 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_1_1_fu_372_p2,
        din1 => mul_1_2_reg_1035,
        dout => acc_1_1_2_fu_376_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U7 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_1_2_reg_1040,
        din1 => mul_2_fu_422_p2,
        dout => acc_1_2_fu_381_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U8 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_2_fu_381_p2,
        din1 => mul_2_1_fu_427_p2,
        dout => acc_1_2_1_fu_385_p2);

    fadd_32ns_32ns_32_1_full_dsp_1_U9 : component conv2d_fadd_32ns_32ns_32_1_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => acc_1_2_1_reg_1045,
        din1 => mul_2_2_reg_1050,
        dout => acc_1_2_2_fu_390_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U10 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_load_1_0_0_fu_186,
        din1 => empty_reg_931,
        dout => mul_fu_394_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U11 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_0_2,
        din1 => empty_24_reg_936,
        dout => mul_0_1_fu_399_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U12 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => line_buf_0_q0,
        din1 => empty_25_reg_941,
        dout => mul_0_2_fu_404_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U13 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_load_1_1_0_fu_182,
        din1 => empty_26_reg_946,
        dout => mul_1_fu_409_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U14 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_1_2,
        din1 => empty_27_reg_951,
        dout => mul_1_1_fu_414_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U15 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => line_buf_1_load_reg_1009,
        din1 => empty_28_reg_956,
        dout => mul_1_2_fu_418_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U16 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_load_1_2_0_fu_178,
        din1 => empty_29_reg_961,
        dout => mul_2_fu_422_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U17 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => window_2_2,
        din1 => empty_30_reg_966,
        dout => mul_2_1_fu_427_p2);

    fmul_32ns_32ns_32_1_max_dsp_1_U18 : component conv2d_fmul_32ns_32ns_32_1_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => new_pixel_1_reg_341_pp0_iter3_reg,
        din1 => empty_31_reg_971,
        dout => mul_2_2_fu_432_p2);

    mul_32ns_32ns_64_1_1_U19 : component conv2d_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound_fu_501_p0,
        din1 => bound_fu_501_p1,
        dout => bound_fu_501_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_pkt_last_V_reg_1004_pp0_iter4_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    col_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                col_fu_174 <= ap_const_lv9_0;
            elsif (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                col_fu_174 <= add_ln43_fu_771_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_fu_194 <= ap_const_lv64_0;
            elsif (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_fu_194 <= add_ln41_fu_602_p2;
            end if; 
        end if;
    end process;

    new_pixel_1_reg_341_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_309)) then
                if (((ap_const_lv1_0 = and_ln55_1_fu_723_p2) and (icmp_ln41_fu_597_p2 = ap_const_lv1_0))) then 
                    new_pixel_1_reg_341 <= ap_const_lv32_0;
                elsif (((ap_const_lv1_1 = and_ln55_1_fu_723_p2) and (icmp_ln41_fu_597_p2 = ap_const_lv1_0))) then 
                    new_pixel_1_reg_341 <= new_pixel_fu_733_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    new_pixel_1_reg_341 <= ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
                end if;
            end if; 
        end if;
    end process;

    row_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                row_fu_190 <= ap_const_lv31_0;
            elsif (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                row_fu_190 <= select_ln41_4_fu_692_p3;
            end if; 
        end if;
    end process;

    window_load_1_0_0_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_load_1_0_0_fu_186 <= window_0_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                window_load_1_0_0_fu_186 <= window_0_2;
            end if; 
        end if;
    end process;

    window_load_1_1_0_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_load_1_1_0_fu_182 <= window_1_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                window_load_1_1_0_fu_182 <= window_1_2;
            end if; 
        end if;
    end process;

    window_load_1_2_0_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_load_1_2_0_fu_178 <= window_2_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                window_load_1_2_0_fu_178 <= window_2_2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln74_reg_1000) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_1_0_1_reg_1015 <= acc_1_0_1_fu_358_p2;
                mul_0_2_reg_1020 <= mul_0_2_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_1_1_2_reg_1040 <= acc_1_1_2_fu_376_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_1_1_reg_1025 <= acc_1_1_fu_367_p2;
                mul_1_1_reg_1030 <= mul_1_1_fu_414_p2;
                mul_1_2_reg_1035 <= mul_1_2_fu_418_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter3_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_1_2_1_reg_1045 <= acc_1_2_1_fu_385_p2;
                mul_2_2_reg_1050 <= mul_2_2_fu_432_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add13_reg_921 <= add13_fu_443_p2;
                bound_reg_976 <= bound_fu_501_p2;
                empty_24_reg_936 <= empty_24_fu_465_p1;
                empty_25_reg_941 <= empty_25_fu_469_p1;
                empty_26_reg_946 <= empty_26_fu_473_p1;
                empty_27_reg_951 <= empty_27_fu_477_p1;
                empty_28_reg_956 <= empty_28_fu_481_p1;
                empty_29_reg_961 <= empty_29_fu_485_p1;
                empty_30_reg_966 <= empty_30_fu_489_p1;
                empty_31_reg_971 <= empty_31_fu_493_p1;
                empty_reg_931 <= empty_fu_461_p1;
                virt_size_reg_916 <= virt_size_fu_437_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln74_reg_1000 <= and_ln74_fu_754_p2;
                line_buf_0_addr_reg_989 <= zext_ln43_fu_700_p1(8 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln74_reg_1000_pp0_iter1_reg <= and_ln74_reg_1000;
                icmp_ln41_reg_981 <= icmp_ln41_fu_597_p2;
                icmp_ln41_reg_981_pp0_iter1_reg <= icmp_ln41_reg_981;
                new_pixel_1_reg_341_pp0_iter1_reg <= new_pixel_1_reg_341;
                out_pkt_last_V_reg_1004_pp0_iter1_reg <= out_pkt_last_V_reg_1004;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln74_reg_1000_pp0_iter2_reg <= and_ln74_reg_1000_pp0_iter1_reg;
                and_ln74_reg_1000_pp0_iter3_reg <= and_ln74_reg_1000_pp0_iter2_reg;
                and_ln74_reg_1000_pp0_iter4_reg <= and_ln74_reg_1000_pp0_iter3_reg;
                and_ln74_reg_1000_pp0_iter5_reg <= and_ln74_reg_1000_pp0_iter4_reg;
                icmp_ln41_reg_981_pp0_iter2_reg <= icmp_ln41_reg_981_pp0_iter1_reg;
                icmp_ln41_reg_981_pp0_iter3_reg <= icmp_ln41_reg_981_pp0_iter2_reg;
                new_pixel_1_reg_341_pp0_iter2_reg <= new_pixel_1_reg_341_pp0_iter1_reg;
                new_pixel_1_reg_341_pp0_iter3_reg <= new_pixel_1_reg_341_pp0_iter2_reg;
                out_pkt_last_V_reg_1004_pp0_iter2_reg <= out_pkt_last_V_reg_1004_pp0_iter1_reg;
                out_pkt_last_V_reg_1004_pp0_iter3_reg <= out_pkt_last_V_reg_1004_pp0_iter2_reg;
                out_pkt_last_V_reg_1004_pp0_iter4_reg <= out_pkt_last_V_reg_1004_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                line_buf_1_load_reg_1009 <= line_buf_1_q1;
                window_0_2 <= line_buf_0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln74_fu_754_p2) and (icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_pkt_last_V_reg_1004 <= out_pkt_last_V_fu_765_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln41_reg_981 = ap_const_lv1_0))) then
                window_0_1 <= window_0_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln41_reg_981_pp0_iter1_reg = ap_const_lv1_0))) then
                window_1_1 <= window_1_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                window_1_2 <= line_buf_1_load_reg_1009;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln41_reg_981_pp0_iter3_reg = ap_const_lv1_0))) then
                window_2_1 <= window_2_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                window_2_2 <= new_pixel_1_reg_341_pp0_iter3_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln41_fu_597_p2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_CS_fsm_state9, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln41_fu_597_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln41_fu_597_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add13_fu_443_p2 <= std_logic_vector(unsigned(img_size) + unsigned(ap_const_lv32_1));
    add_ln41_1_fu_608_p2 <= std_logic_vector(unsigned(row_fu_190) + unsigned(ap_const_lv31_1));
    add_ln41_fu_602_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_194) + unsigned(ap_const_lv64_1));
    add_ln43_fu_771_p2 <= std_logic_vector(unsigned(select_ln41_fu_618_p3) + unsigned(ap_const_lv9_1));
    and_ln55_1_fu_723_p2 <= (select_ln41_3_fu_680_p3 and and_ln55_2_fu_717_p2);
    and_ln55_2_fu_717_p2 <= (icmp_ln56_fu_706_p2 and icmp_ln56_1_fu_712_p2);
    and_ln55_3_fu_674_p2 <= (notrhs_mid1_fu_669_p2 and notlhs_mid1_fu_663_p2);
    and_ln55_fu_582_p2 <= (notrhs_fu_577_p2 and notlhs_fu_571_p2);
    and_ln74_fu_754_p2 <= (select_ln41_1_fu_642_p3 and icmp_ln74_fu_748_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state9 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, and_ln74_reg_1000_pp0_iter4_reg, ap_enable_reg_pp0_iter6, and_ln74_reg_1000_pp0_iter5_reg, ap_predicate_op124_read_state2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op124_read_state2 = ap_const_boolean_1)) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, and_ln74_reg_1000_pp0_iter4_reg, ap_enable_reg_pp0_iter6, and_ln74_reg_1000_pp0_iter5_reg, ap_predicate_op124_read_state2, ap_block_state7_io, ap_block_state8_io, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op124_read_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, and_ln74_reg_1000_pp0_iter4_reg, ap_enable_reg_pp0_iter6, and_ln74_reg_1000_pp0_iter5_reg, ap_predicate_op124_read_state2, ap_block_state7_io, ap_block_state8_io, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op124_read_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(ap_predicate_op124_read_state2, in_stream_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op124_read_state2 = ap_const_boolean_1));
    end process;

        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_io_assign_proc : process(and_ln74_reg_1000_pp0_iter4_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state7_io <= ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state7_pp0_stage0_iter5_assign_proc : process(and_ln74_reg_1000_pp0_iter4_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage0_iter5 <= ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state8_io_assign_proc : process(and_ln74_reg_1000_pp0_iter5_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state8_io <= ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state8_pp0_stage0_iter6_assign_proc : process(and_ln74_reg_1000_pp0_iter5_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state8_pp0_stage0_iter6 <= ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_309_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_309 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln41_fu_597_p2)
    begin
        if ((icmp_ln41_fu_597_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state9, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_new_pixel_1_phi_fu_344_p4_assign_proc : process(icmp_ln41_fu_597_p2, and_ln55_1_fu_723_p2, new_pixel_fu_733_p1, ap_phi_reg_pp0_iter0_new_pixel_1_reg_341)
    begin
        if ((icmp_ln41_fu_597_p2 = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln55_1_fu_723_p2)) then 
                ap_phi_mux_new_pixel_1_phi_fu_344_p4 <= ap_const_lv32_0;
            elsif ((ap_const_lv1_1 = and_ln55_1_fu_723_p2)) then 
                ap_phi_mux_new_pixel_1_phi_fu_344_p4 <= new_pixel_fu_733_p1;
            else 
                ap_phi_mux_new_pixel_1_phi_fu_344_p4 <= ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
            end if;
        else 
            ap_phi_mux_new_pixel_1_phi_fu_344_p4 <= ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_new_pixel_1_reg_341 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op124_read_state2_assign_proc : process(icmp_ln41_fu_597_p2, and_ln55_1_fu_723_p2)
    begin
                ap_predicate_op124_read_state2 <= ((ap_const_lv1_1 = and_ln55_1_fu_723_p2) and (icmp_ln41_fu_597_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bound_fu_501_p0 <= cast_fu_497_p1(32 - 1 downto 0);
    bound_fu_501_p1 <= cast_fu_497_p1(32 - 1 downto 0);
    cast_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(virt_size_fu_437_p2),64));
    cmp69_fu_566_p2 <= "1" when (zext_ln41_1_fu_546_p1 = add13_reg_921) else "0";
    cmp69_mid1_fu_650_p2 <= "1" when (zext_ln41_fu_614_p1 = add13_reg_921) else "0";
    empty_24_fu_465_p1 <= kernel_in_2_1;
    empty_25_fu_469_p1 <= kernel_in_2_0;
    empty_26_fu_473_p1 <= kernel_in_1_2;
    empty_27_fu_477_p1 <= kernel_in_1_1;
    empty_28_fu_481_p1 <= kernel_in_1_0;
    empty_29_fu_485_p1 <= kernel_in_0_2;
    empty_30_fu_489_p1 <= kernel_in_0_1;
    empty_31_fu_493_p1 <= kernel_in_0_0;
    empty_fu_461_p1 <= kernel_in_2_2;
    icmp19_fu_636_p2 <= "0" when (tmp_1_fu_626_p4 = ap_const_lv30_0) else "1";
    icmp_fu_560_p2 <= "0" when (tmp_fu_550_p4 = ap_const_lv30_0) else "1";
    icmp_ln41_fu_597_p2 <= "1" when (indvar_flatten_fu_194 = bound_reg_976) else "0";
    icmp_ln43_fu_592_p2 <= "1" when (zext_ln43_1_fu_588_p1 = virt_size_reg_916) else "0";
    icmp_ln56_1_fu_712_p2 <= "1" when (signed(zext_ln41_2_fu_688_p1) < signed(add13_reg_921)) else "0";
    icmp_ln56_fu_706_p2 <= "0" when (select_ln41_fu_618_p3 = ap_const_lv9_0) else "1";
    icmp_ln74_fu_748_p2 <= "0" when (tmp_3_fu_738_p4 = ap_const_lv8_0) else "1";
    icmp_ln92_fu_760_p2 <= "1" when (zext_ln41_2_fu_688_p1 = add13_reg_921) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln41_fu_597_p2, and_ln55_1_fu_723_p2, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_lv1_1 = and_ln55_1_fu_723_p2) and (icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op124_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op124_read_state2 = ap_const_boolean_1))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_0_address0 <= zext_ln43_fu_700_p1(8 - 1 downto 0);

    line_buf_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_0_ce0 <= ap_const_logic_1;
        else 
            line_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_0_ce1 <= ap_const_logic_1;
        else 
            line_buf_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_0_we1 <= ap_const_logic_1;
        else 
            line_buf_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_1_address1 <= zext_ln43_fu_700_p1(8 - 1 downto 0);

    line_buf_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln41_fu_597_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_1_ce1 <= ap_const_logic_1;
        else 
            line_buf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln41_fu_597_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln41_fu_597_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_1_we1 <= ap_const_logic_1;
        else 
            line_buf_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    new_pixel_fu_733_p1 <= in_stream_TDATA_int_regslice;
    notlhs_fu_571_p2 <= "0" when (row_fu_190 = ap_const_lv31_0) else "1";
    notlhs_mid1_fu_663_p2 <= "0" when (add_ln41_1_fu_608_p2 = ap_const_lv31_0) else "1";
    notrhs_fu_577_p2 <= "1" when (signed(zext_ln41_1_fu_546_p1) < signed(add13_reg_921)) else "0";
    notrhs_mid1_fu_669_p2 <= "1" when (signed(zext_ln41_fu_614_p1) < signed(add13_reg_921)) else "0";
    out_pkt_last_V_fu_765_p2 <= (select_ln41_2_fu_655_p3 and icmp_ln92_fu_760_p2);

    out_stream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, and_ln74_reg_1000_pp0_iter4_reg, ap_enable_reg_pp0_iter6, and_ln74_reg_1000_pp0_iter5_reg, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter5_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= acc_1_2_2_fu_390_p2;
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter5, and_ln74_reg_1000_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_1 = and_ln74_reg_1000_pp0_iter4_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln41_1_fu_642_p3 <= 
        icmp19_fu_636_p2 when (icmp_ln43_fu_592_p2(0) = '1') else 
        icmp_fu_560_p2;
    select_ln41_2_fu_655_p3 <= 
        cmp69_mid1_fu_650_p2 when (icmp_ln43_fu_592_p2(0) = '1') else 
        cmp69_fu_566_p2;
    select_ln41_3_fu_680_p3 <= 
        and_ln55_3_fu_674_p2 when (icmp_ln43_fu_592_p2(0) = '1') else 
        and_ln55_fu_582_p2;
    select_ln41_4_fu_692_p3 <= 
        add_ln41_1_fu_608_p2 when (icmp_ln43_fu_592_p2(0) = '1') else 
        row_fu_190;
    select_ln41_fu_618_p3 <= 
        ap_const_lv9_0 when (icmp_ln43_fu_592_p2(0) = '1') else 
        col_fu_174;
    tmp_1_fu_626_p4 <= add_ln41_1_fu_608_p2(30 downto 1);
    tmp_3_fu_738_p4 <= select_ln41_fu_618_p3(8 downto 1);
    tmp_fu_550_p4 <= row_fu_190(30 downto 1);
    virt_size_fu_437_p2 <= std_logic_vector(unsigned(img_size) + unsigned(ap_const_lv32_2));
    zext_ln41_1_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_fu_190),32));
    zext_ln41_2_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln41_fu_618_p3),32));
    zext_ln41_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_1_fu_608_p2),32));
    zext_ln43_1_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_fu_174),32));
    zext_ln43_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln41_fu_618_p3),64));
end behav;
