// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_conv2d,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=250.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=239.745000,HLS_SYN_LAT=9611,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1821,HLS_SYN_LUT=7833,HLS_VERSION=2021_1}" *)

module conv2d (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state9 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] kernel_in_0_0;
wire   [31:0] kernel_in_0_1;
wire   [31:0] kernel_in_0_2;
wire   [31:0] kernel_in_1_0;
wire   [31:0] kernel_in_1_1;
wire   [31:0] kernel_in_1_2;
wire   [31:0] kernel_in_2_0;
wire   [31:0] kernel_in_2_1;
wire   [31:0] kernel_in_2_2;
wire   [31:0] img_size;
reg   [31:0] window_0_1;
reg   [31:0] window_1_1;
reg   [31:0] window_2_1;
wire   [7:0] line_buf_0_address0;
reg    line_buf_0_ce0;
wire   [31:0] line_buf_0_q0;
reg    line_buf_0_ce1;
reg    line_buf_0_we1;
reg   [31:0] window_0_2;
wire   [7:0] line_buf_1_address1;
reg    line_buf_1_ce1;
reg    line_buf_1_we1;
wire   [31:0] line_buf_1_q1;
reg   [31:0] window_1_2;
reg   [31:0] window_2_2;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln41_fu_597_p2;
wire   [0:0] and_ln55_1_fu_723_p2;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] and_ln74_reg_1000;
reg   [0:0] and_ln74_reg_1000_pp0_iter4_reg;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] and_ln74_reg_1000_pp0_iter5_reg;
reg   [31:0] new_pixel_1_reg_341;
reg   [31:0] new_pixel_1_reg_341_pp0_iter1_reg;
reg    ap_predicate_op124_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_state7_io;
reg    ap_block_state8_pp0_stage0_iter6;
reg    ap_block_state8_io;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] new_pixel_1_reg_341_pp0_iter2_reg;
reg   [31:0] new_pixel_1_reg_341_pp0_iter3_reg;
wire   [31:0] virt_size_fu_437_p2;
reg   [31:0] virt_size_reg_916;
wire   [31:0] add13_fu_443_p2;
reg   [31:0] add13_reg_921;
wire   [31:0] empty_fu_461_p1;
reg   [31:0] empty_reg_931;
wire   [31:0] empty_24_fu_465_p1;
reg   [31:0] empty_24_reg_936;
wire   [31:0] empty_25_fu_469_p1;
reg   [31:0] empty_25_reg_941;
wire   [31:0] empty_26_fu_473_p1;
reg   [31:0] empty_26_reg_946;
wire   [31:0] empty_27_fu_477_p1;
reg   [31:0] empty_27_reg_951;
wire   [31:0] empty_28_fu_481_p1;
reg   [31:0] empty_28_reg_956;
wire   [31:0] empty_29_fu_485_p1;
reg   [31:0] empty_29_reg_961;
wire   [31:0] empty_30_fu_489_p1;
reg   [31:0] empty_30_reg_966;
wire   [31:0] empty_31_fu_493_p1;
reg   [31:0] empty_31_reg_971;
wire   [63:0] bound_fu_501_p2;
reg   [63:0] bound_reg_976;
reg   [0:0] icmp_ln41_reg_981;
reg   [0:0] icmp_ln41_reg_981_pp0_iter1_reg;
reg   [0:0] icmp_ln41_reg_981_pp0_iter2_reg;
reg   [0:0] icmp_ln41_reg_981_pp0_iter3_reg;
reg   [7:0] line_buf_0_addr_reg_989;
wire   [0:0] and_ln74_fu_754_p2;
reg   [0:0] and_ln74_reg_1000_pp0_iter1_reg;
reg   [0:0] and_ln74_reg_1000_pp0_iter2_reg;
reg   [0:0] and_ln74_reg_1000_pp0_iter3_reg;
wire   [0:0] out_pkt_last_V_fu_765_p2;
reg   [0:0] out_pkt_last_V_reg_1004;
reg   [0:0] out_pkt_last_V_reg_1004_pp0_iter1_reg;
reg   [0:0] out_pkt_last_V_reg_1004_pp0_iter2_reg;
reg   [0:0] out_pkt_last_V_reg_1004_pp0_iter3_reg;
reg   [0:0] out_pkt_last_V_reg_1004_pp0_iter4_reg;
reg   [31:0] line_buf_1_load_reg_1009;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] acc_1_0_1_fu_358_p2;
reg   [31:0] acc_1_0_1_reg_1015;
wire   [31:0] mul_0_2_fu_404_p2;
reg   [31:0] mul_0_2_reg_1020;
wire   [31:0] acc_1_1_fu_367_p2;
reg   [31:0] acc_1_1_reg_1025;
wire   [31:0] mul_1_1_fu_414_p2;
reg   [31:0] mul_1_1_reg_1030;
wire   [31:0] mul_1_2_fu_418_p2;
reg   [31:0] mul_1_2_reg_1035;
wire   [31:0] acc_1_1_2_fu_376_p2;
reg   [31:0] acc_1_1_2_reg_1040;
wire   [31:0] acc_1_2_1_fu_385_p2;
reg   [31:0] acc_1_2_1_reg_1045;
wire   [31:0] mul_2_2_fu_432_p2;
reg   [31:0] mul_2_2_reg_1050;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] ap_phi_mux_new_pixel_1_phi_fu_344_p4;
wire   [31:0] new_pixel_fu_733_p1;
wire   [31:0] ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
wire   [63:0] zext_ln43_fu_700_p1;
reg   [8:0] col_fu_174;
wire   [8:0] add_ln43_fu_771_p2;
reg   [31:0] window_load_1_2_0_fu_178;
reg   [31:0] window_load_1_1_0_fu_182;
reg   [31:0] window_load_1_0_0_fu_186;
reg   [30:0] row_fu_190;
wire   [30:0] select_ln41_4_fu_692_p3;
reg   [63:0] indvar_flatten_fu_194;
wire   [63:0] add_ln41_fu_602_p2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] mul_fu_394_p2;
wire   [31:0] acc_1_fu_353_p2;
wire   [31:0] mul_0_1_fu_399_p2;
wire   [31:0] acc_1_0_2_fu_363_p2;
wire   [31:0] mul_1_fu_409_p2;
wire   [31:0] acc_1_1_1_fu_372_p2;
wire   [31:0] mul_2_fu_422_p2;
wire   [31:0] acc_1_2_fu_381_p2;
wire   [31:0] mul_2_1_fu_427_p2;
wire   [31:0] bound_fu_501_p0;
wire   [63:0] cast_fu_497_p1;
wire   [31:0] bound_fu_501_p1;
wire   [29:0] tmp_fu_550_p4;
wire   [31:0] zext_ln41_1_fu_546_p1;
wire   [0:0] notrhs_fu_577_p2;
wire   [0:0] notlhs_fu_571_p2;
wire   [31:0] zext_ln43_1_fu_588_p1;
wire   [30:0] add_ln41_1_fu_608_p2;
wire   [0:0] icmp_ln43_fu_592_p2;
wire   [29:0] tmp_1_fu_626_p4;
wire   [0:0] icmp19_fu_636_p2;
wire   [0:0] icmp_fu_560_p2;
wire   [31:0] zext_ln41_fu_614_p1;
wire   [0:0] cmp69_mid1_fu_650_p2;
wire   [0:0] cmp69_fu_566_p2;
wire   [0:0] notrhs_mid1_fu_669_p2;
wire   [0:0] notlhs_mid1_fu_663_p2;
wire   [0:0] and_ln55_3_fu_674_p2;
wire   [0:0] and_ln55_fu_582_p2;
wire   [8:0] select_ln41_fu_618_p3;
wire   [31:0] zext_ln41_2_fu_688_p1;
wire   [0:0] icmp_ln56_fu_706_p2;
wire   [0:0] icmp_ln56_1_fu_712_p2;
wire   [0:0] and_ln55_2_fu_717_p2;
wire   [0:0] select_ln41_3_fu_680_p3;
wire   [7:0] tmp_3_fu_738_p4;
wire   [0:0] select_ln41_1_fu_642_p3;
wire   [0:0] icmp_ln74_fu_748_p2;
wire   [0:0] select_ln41_2_fu_655_p3;
wire   [0:0] icmp_ln92_fu_760_p2;
wire   [31:0] acc_1_2_2_fu_390_p2;
wire    ap_CS_fsm_state9;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
reg    ap_condition_309;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 window_0_1 = 32'd0;
#0 window_1_1 = 32'd0;
#0 window_2_1 = 32'd0;
#0 window_0_2 = 32'd0;
#0 window_1_2 = 32'd0;
#0 window_2_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

conv2d_line_buf_0 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_0_address0),
    .ce0(line_buf_0_ce0),
    .q0(line_buf_0_q0),
    .address1(line_buf_0_addr_reg_989),
    .ce1(line_buf_0_ce1),
    .we1(line_buf_0_we1),
    .d1(line_buf_1_q1)
);

conv2d_line_buf_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address1(line_buf_1_address1),
    .ce1(line_buf_1_ce1),
    .we1(line_buf_1_we1),
    .d1(ap_phi_mux_new_pixel_1_phi_fu_344_p4),
    .q1(line_buf_1_q1)
);

conv2d_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .kernel_in_0_0(kernel_in_0_0),
    .kernel_in_0_1(kernel_in_0_1),
    .kernel_in_0_2(kernel_in_0_2),
    .kernel_in_1_0(kernel_in_1_0),
    .kernel_in_1_1(kernel_in_1_1),
    .kernel_in_1_2(kernel_in_1_2),
    .kernel_in_2_0(kernel_in_2_0),
    .kernel_in_2_1(kernel_in_2_1),
    .kernel_in_2_2(kernel_in_2_2),
    .img_size(img_size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U1(
    .din0(mul_fu_394_p2),
    .din1(32'd0),
    .dout(acc_1_fu_353_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U2(
    .din0(acc_1_fu_353_p2),
    .din1(mul_0_1_fu_399_p2),
    .dout(acc_1_0_1_fu_358_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U3(
    .din0(acc_1_0_1_reg_1015),
    .din1(mul_0_2_reg_1020),
    .dout(acc_1_0_2_fu_363_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U4(
    .din0(acc_1_0_2_fu_363_p2),
    .din1(mul_1_fu_409_p2),
    .dout(acc_1_1_fu_367_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U5(
    .din0(acc_1_1_reg_1025),
    .din1(mul_1_1_reg_1030),
    .dout(acc_1_1_1_fu_372_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U6(
    .din0(acc_1_1_1_fu_372_p2),
    .din1(mul_1_2_reg_1035),
    .dout(acc_1_1_2_fu_376_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U7(
    .din0(acc_1_1_2_reg_1040),
    .din1(mul_2_fu_422_p2),
    .dout(acc_1_2_fu_381_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U8(
    .din0(acc_1_2_fu_381_p2),
    .din1(mul_2_1_fu_427_p2),
    .dout(acc_1_2_1_fu_385_p2)
);

conv2d_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U9(
    .din0(acc_1_2_1_reg_1045),
    .din1(mul_2_2_reg_1050),
    .dout(acc_1_2_2_fu_390_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U10(
    .din0(window_load_1_0_0_fu_186),
    .din1(empty_reg_931),
    .dout(mul_fu_394_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U11(
    .din0(window_0_2),
    .din1(empty_24_reg_936),
    .dout(mul_0_1_fu_399_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U12(
    .din0(line_buf_0_q0),
    .din1(empty_25_reg_941),
    .dout(mul_0_2_fu_404_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U13(
    .din0(window_load_1_1_0_fu_182),
    .din1(empty_26_reg_946),
    .dout(mul_1_fu_409_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U14(
    .din0(window_1_2),
    .din1(empty_27_reg_951),
    .dout(mul_1_1_fu_414_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U15(
    .din0(line_buf_1_load_reg_1009),
    .din1(empty_28_reg_956),
    .dout(mul_1_2_fu_418_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U16(
    .din0(window_load_1_2_0_fu_178),
    .din1(empty_29_reg_961),
    .dout(mul_2_fu_422_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U17(
    .din0(window_2_2),
    .din1(empty_30_reg_966),
    .dout(mul_2_1_fu_427_p2)
);

conv2d_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U18(
    .din0(new_pixel_1_reg_341_pp0_iter3_reg),
    .din1(empty_31_reg_971),
    .dout(mul_2_2_fu_432_p2)
);

conv2d_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U19(
    .din0(bound_fu_501_p0),
    .din1(bound_fu_501_p1),
    .dout(bound_fu_501_p2)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pkt_last_V_reg_1004_pp0_iter4_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_fu_174 <= 9'd0;
    end else if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_fu_174 <= add_ln43_fu_771_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_194 <= 64'd0;
    end else if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_194 <= add_ln41_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_309)) begin
        if (((1'd0 == and_ln55_1_fu_723_p2) & (icmp_ln41_fu_597_p2 == 1'd0))) begin
            new_pixel_1_reg_341 <= 32'd0;
        end else if (((1'd1 == and_ln55_1_fu_723_p2) & (icmp_ln41_fu_597_p2 == 1'd0))) begin
            new_pixel_1_reg_341 <= new_pixel_fu_733_p1;
        end else if ((1'b1 == 1'b1)) begin
            new_pixel_1_reg_341 <= ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_fu_190 <= 31'd0;
    end else if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_fu_190 <= select_ln41_4_fu_692_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_load_1_0_0_fu_186 <= window_0_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_load_1_0_0_fu_186 <= window_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_load_1_1_0_fu_182 <= window_1_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        window_load_1_1_0_fu_182 <= window_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        window_load_1_2_0_fu_178 <= window_2_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        window_load_1_2_0_fu_178 <= window_2_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln74_reg_1000) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_1_0_1_reg_1015 <= acc_1_0_1_fu_358_p2;
        mul_0_2_reg_1020 <= mul_0_2_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln74_reg_1000_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_1_2_reg_1040 <= acc_1_1_2_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln74_reg_1000_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_1_reg_1025 <= acc_1_1_fu_367_p2;
        mul_1_1_reg_1030 <= mul_1_1_fu_414_p2;
        mul_1_2_reg_1035 <= mul_1_2_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln74_reg_1000_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_2_1_reg_1045 <= acc_1_2_1_fu_385_p2;
        mul_2_2_reg_1050 <= mul_2_2_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add13_reg_921 <= add13_fu_443_p2;
        bound_reg_976 <= bound_fu_501_p2;
        empty_24_reg_936 <= empty_24_fu_465_p1;
        empty_25_reg_941 <= empty_25_fu_469_p1;
        empty_26_reg_946 <= empty_26_fu_473_p1;
        empty_27_reg_951 <= empty_27_fu_477_p1;
        empty_28_reg_956 <= empty_28_fu_481_p1;
        empty_29_reg_961 <= empty_29_fu_485_p1;
        empty_30_reg_966 <= empty_30_fu_489_p1;
        empty_31_reg_971 <= empty_31_fu_493_p1;
        empty_reg_931 <= empty_fu_461_p1;
        virt_size_reg_916 <= virt_size_fu_437_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln74_reg_1000 <= and_ln74_fu_754_p2;
        line_buf_0_addr_reg_989 <= zext_ln43_fu_700_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln74_reg_1000_pp0_iter1_reg <= and_ln74_reg_1000;
        icmp_ln41_reg_981 <= icmp_ln41_fu_597_p2;
        icmp_ln41_reg_981_pp0_iter1_reg <= icmp_ln41_reg_981;
        new_pixel_1_reg_341_pp0_iter1_reg <= new_pixel_1_reg_341;
        out_pkt_last_V_reg_1004_pp0_iter1_reg <= out_pkt_last_V_reg_1004;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln74_reg_1000_pp0_iter2_reg <= and_ln74_reg_1000_pp0_iter1_reg;
        and_ln74_reg_1000_pp0_iter3_reg <= and_ln74_reg_1000_pp0_iter2_reg;
        and_ln74_reg_1000_pp0_iter4_reg <= and_ln74_reg_1000_pp0_iter3_reg;
        and_ln74_reg_1000_pp0_iter5_reg <= and_ln74_reg_1000_pp0_iter4_reg;
        icmp_ln41_reg_981_pp0_iter2_reg <= icmp_ln41_reg_981_pp0_iter1_reg;
        icmp_ln41_reg_981_pp0_iter3_reg <= icmp_ln41_reg_981_pp0_iter2_reg;
        new_pixel_1_reg_341_pp0_iter2_reg <= new_pixel_1_reg_341_pp0_iter1_reg;
        new_pixel_1_reg_341_pp0_iter3_reg <= new_pixel_1_reg_341_pp0_iter2_reg;
        out_pkt_last_V_reg_1004_pp0_iter2_reg <= out_pkt_last_V_reg_1004_pp0_iter1_reg;
        out_pkt_last_V_reg_1004_pp0_iter3_reg <= out_pkt_last_V_reg_1004_pp0_iter2_reg;
        out_pkt_last_V_reg_1004_pp0_iter4_reg <= out_pkt_last_V_reg_1004_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_load_reg_1009 <= line_buf_1_q1;
        window_0_2 <= line_buf_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln74_fu_754_p2) & (icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_pkt_last_V_reg_1004 <= out_pkt_last_V_fu_765_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln41_reg_981 == 1'd0))) begin
        window_0_1 <= window_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln41_reg_981_pp0_iter1_reg == 1'd0))) begin
        window_1_1 <= window_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        window_1_2 <= line_buf_1_load_reg_1009;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln41_reg_981_pp0_iter3_reg == 1'd0))) begin
        window_2_1 <= window_2_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        window_2_2 <= new_pixel_1_reg_341_pp0_iter3_reg;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_597_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_597_p2 == 1'd0)) begin
        if ((1'd0 == and_ln55_1_fu_723_p2)) begin
            ap_phi_mux_new_pixel_1_phi_fu_344_p4 = 32'd0;
        end else if ((1'd1 == and_ln55_1_fu_723_p2)) begin
            ap_phi_mux_new_pixel_1_phi_fu_344_p4 = new_pixel_fu_733_p1;
        end else begin
            ap_phi_mux_new_pixel_1_phi_fu_344_p4 = ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
        end
    end else begin
        ap_phi_mux_new_pixel_1_phi_fu_344_p4 = ap_phi_reg_pp0_iter0_new_pixel_1_reg_341;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln55_1_fu_723_p2) & (icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op124_read_state2 == 1'b1))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_0_ce0 = 1'b1;
    end else begin
        line_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_0_ce1 = 1'b1;
    end else begin
        line_buf_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_0_we1 = 1'b1;
    end else begin
        line_buf_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce1 = 1'b1;
    end else begin
        line_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_597_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_we1 = 1'b1;
    end else begin
        line_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln41_fu_597_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln41_fu_597_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add13_fu_443_p2 = (img_size + 32'd1);

assign add_ln41_1_fu_608_p2 = (row_fu_190 + 31'd1);

assign add_ln41_fu_602_p2 = (indvar_flatten_fu_194 + 64'd1);

assign add_ln43_fu_771_p2 = (select_ln41_fu_618_p3 + 9'd1);

assign and_ln55_1_fu_723_p2 = (select_ln41_3_fu_680_p3 & and_ln55_2_fu_717_p2);

assign and_ln55_2_fu_717_p2 = (icmp_ln56_fu_706_p2 & icmp_ln56_1_fu_712_p2);

assign and_ln55_3_fu_674_p2 = (notrhs_mid1_fu_669_p2 & notlhs_mid1_fu_663_p2);

assign and_ln55_fu_582_p2 = (notrhs_fu_577_p2 & notlhs_fu_571_p2);

assign and_ln74_fu_754_p2 = (select_ln41_1_fu_642_p3 & icmp_ln74_fu_748_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op124_read_state2 == 1'b1)) | ((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op124_read_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state7_io) | ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (out_stream_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op124_read_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state7_io) | ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (out_stream_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((in_stream_TVALID_int_regslice == 1'b0) & (ap_predicate_op124_read_state2 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = ((1'd1 == and_ln74_reg_1000_pp0_iter4_reg) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state8_io = ((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter6 = ((1'd1 == and_ln74_reg_1000_pp0_iter5_reg) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_309 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_new_pixel_1_reg_341 = 'bx;

always @ (*) begin
    ap_predicate_op124_read_state2 = ((1'd1 == and_ln55_1_fu_723_p2) & (icmp_ln41_fu_597_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_501_p0 = cast_fu_497_p1;

assign bound_fu_501_p1 = cast_fu_497_p1;

assign cast_fu_497_p1 = virt_size_fu_437_p2;

assign cmp69_fu_566_p2 = ((zext_ln41_1_fu_546_p1 == add13_reg_921) ? 1'b1 : 1'b0);

assign cmp69_mid1_fu_650_p2 = ((zext_ln41_fu_614_p1 == add13_reg_921) ? 1'b1 : 1'b0);

assign empty_24_fu_465_p1 = kernel_in_2_1;

assign empty_25_fu_469_p1 = kernel_in_2_0;

assign empty_26_fu_473_p1 = kernel_in_1_2;

assign empty_27_fu_477_p1 = kernel_in_1_1;

assign empty_28_fu_481_p1 = kernel_in_1_0;

assign empty_29_fu_485_p1 = kernel_in_0_2;

assign empty_30_fu_489_p1 = kernel_in_0_1;

assign empty_31_fu_493_p1 = kernel_in_0_0;

assign empty_fu_461_p1 = kernel_in_2_2;

assign icmp19_fu_636_p2 = ((tmp_1_fu_626_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_fu_560_p2 = ((tmp_fu_550_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_597_p2 = ((indvar_flatten_fu_194 == bound_reg_976) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_592_p2 = ((zext_ln43_1_fu_588_p1 == virt_size_reg_916) ? 1'b1 : 1'b0);

assign icmp_ln56_1_fu_712_p2 = (($signed(zext_ln41_2_fu_688_p1) < $signed(add13_reg_921)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_706_p2 = ((select_ln41_fu_618_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_748_p2 = ((tmp_3_fu_738_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_760_p2 = ((zext_ln41_2_fu_688_p1 == add13_reg_921) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign line_buf_0_address0 = zext_ln43_fu_700_p1;

assign line_buf_1_address1 = zext_ln43_fu_700_p1;

assign new_pixel_fu_733_p1 = in_stream_TDATA_int_regslice;

assign notlhs_fu_571_p2 = ((row_fu_190 != 31'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_663_p2 = ((add_ln41_1_fu_608_p2 != 31'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_577_p2 = (($signed(zext_ln41_1_fu_546_p1) < $signed(add13_reg_921)) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_669_p2 = (($signed(zext_ln41_fu_614_p1) < $signed(add13_reg_921)) ? 1'b1 : 1'b0);

assign out_pkt_last_V_fu_765_p2 = (select_ln41_2_fu_655_p3 & icmp_ln92_fu_760_p2);

assign out_stream_TDATA_int_regslice = acc_1_2_2_fu_390_p2;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign select_ln41_1_fu_642_p3 = ((icmp_ln43_fu_592_p2[0:0] == 1'b1) ? icmp19_fu_636_p2 : icmp_fu_560_p2);

assign select_ln41_2_fu_655_p3 = ((icmp_ln43_fu_592_p2[0:0] == 1'b1) ? cmp69_mid1_fu_650_p2 : cmp69_fu_566_p2);

assign select_ln41_3_fu_680_p3 = ((icmp_ln43_fu_592_p2[0:0] == 1'b1) ? and_ln55_3_fu_674_p2 : and_ln55_fu_582_p2);

assign select_ln41_4_fu_692_p3 = ((icmp_ln43_fu_592_p2[0:0] == 1'b1) ? add_ln41_1_fu_608_p2 : row_fu_190);

assign select_ln41_fu_618_p3 = ((icmp_ln43_fu_592_p2[0:0] == 1'b1) ? 9'd0 : col_fu_174);

assign tmp_1_fu_626_p4 = {{add_ln41_1_fu_608_p2[30:1]}};

assign tmp_3_fu_738_p4 = {{select_ln41_fu_618_p3[8:1]}};

assign tmp_fu_550_p4 = {{row_fu_190[30:1]}};

assign virt_size_fu_437_p2 = (img_size + 32'd2);

assign zext_ln41_1_fu_546_p1 = row_fu_190;

assign zext_ln41_2_fu_688_p1 = select_ln41_fu_618_p3;

assign zext_ln41_fu_614_p1 = add_ln41_1_fu_608_p2;

assign zext_ln43_1_fu_588_p1 = col_fu_174;

assign zext_ln43_fu_700_p1 = select_ln41_fu_618_p3;

endmodule //conv2d
