// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_conv2d,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=86479,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2954,HLS_SYN_LUT=2506,HLS_VERSION=2021_1}" *)

module conv2d (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_pp0_stage0 = 12'd4;
parameter    ap_ST_fsm_pp0_stage1 = 12'd8;
parameter    ap_ST_fsm_pp0_stage2 = 12'd16;
parameter    ap_ST_fsm_pp0_stage3 = 12'd32;
parameter    ap_ST_fsm_pp0_stage4 = 12'd64;
parameter    ap_ST_fsm_pp0_stage5 = 12'd128;
parameter    ap_ST_fsm_pp0_stage6 = 12'd256;
parameter    ap_ST_fsm_pp0_stage7 = 12'd512;
parameter    ap_ST_fsm_pp0_stage8 = 12'd1024;
parameter    ap_ST_fsm_state53 = 12'd2048;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] kernel_in_0_0;
wire   [31:0] kernel_in_0_1;
wire   [31:0] kernel_in_0_2;
wire   [31:0] kernel_in_1_0;
wire   [31:0] kernel_in_1_1;
wire   [31:0] kernel_in_1_2;
wire   [31:0] kernel_in_2_0;
wire   [31:0] kernel_in_2_1;
wire   [31:0] kernel_in_2_2;
wire   [31:0] img_size;
wire   [7:0] line_buf_0_address0;
reg    line_buf_0_ce0;
wire   [31:0] line_buf_0_q0;
reg    line_buf_0_ce1;
reg    line_buf_0_we1;
reg   [31:0] window_0_2;
wire   [7:0] line_buf_1_address0;
reg    line_buf_1_ce0;
wire   [31:0] line_buf_1_q0;
reg    line_buf_1_ce1;
reg    line_buf_1_we1;
reg   [31:0] window_1_2;
reg   [31:0] window_2_2;
reg   [31:0] window_0_1;
reg   [31:0] window_1_1;
reg   [31:0] window_2_1;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln41_reg_955;
reg   [0:0] and_ln55_1_reg_964;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter5;
wire    ap_block_pp0_stage3;
reg   [0:0] and_ln74_reg_980;
reg   [0:0] and_ln74_reg_980_pp0_iter5_reg;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [31:0] new_pixel_1_reg_345;
reg    ap_predicate_op185_read_state4;
reg    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state13_pp0_stage1_iter1;
wire    ap_block_state22_pp0_stage1_iter2;
wire    ap_block_state31_pp0_stage1_iter3;
wire    ap_block_state40_pp0_stage1_iter4;
wire    ap_block_state49_pp0_stage1_iter5;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] img_size_read_reg_839;
wire   [31:0] virt_size_fu_431_p2;
reg   [31:0] virt_size_reg_844;
reg   [31:0] kernel_in_2_2_read_reg_850;
reg   [31:0] kernel_in_2_0_read_reg_855;
reg   [31:0] kernel_in_2_1_read_reg_860;
reg   [31:0] kernel_in_0_2_read_reg_865;
reg   [31:0] kernel_in_0_0_read_reg_870;
reg   [31:0] kernel_in_0_1_read_reg_875;
reg   [31:0] kernel_in_1_2_read_reg_880;
reg   [31:0] kernel_in_1_0_read_reg_885;
reg   [31:0] kernel_in_1_1_read_reg_890;
wire   [31:0] add13_fu_452_p2;
reg   [31:0] add13_reg_895;
wire    ap_CS_fsm_state2;
wire   [31:0] empty_fu_457_p1;
reg   [31:0] empty_reg_905;
wire   [31:0] empty_28_fu_460_p1;
reg   [31:0] empty_28_reg_910;
wire   [31:0] empty_29_fu_463_p1;
reg   [31:0] empty_29_reg_915;
wire   [31:0] empty_30_fu_466_p1;
reg   [31:0] empty_30_reg_920;
wire   [31:0] empty_31_fu_469_p1;
reg   [31:0] empty_31_reg_925;
wire   [31:0] empty_32_fu_472_p1;
reg   [31:0] empty_32_reg_930;
wire   [31:0] empty_33_fu_475_p1;
reg   [31:0] empty_33_reg_935;
wire   [31:0] empty_34_fu_478_p1;
reg   [31:0] empty_34_reg_940;
wire   [31:0] empty_35_fu_481_p1;
reg   [31:0] empty_35_reg_945;
wire   [63:0] bound_fu_487_p2;
reg   [63:0] bound_reg_950;
wire   [0:0] icmp_ln41_fu_553_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state12_pp0_stage0_iter1;
wire    ap_block_state21_pp0_stage0_iter2;
wire    ap_block_state30_pp0_stage0_iter3;
wire    ap_block_state39_pp0_stage0_iter4;
wire    ap_block_state48_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln55_1_fu_684_p2;
reg   [7:0] line_buf_0_addr_reg_968;
reg   [7:0] line_buf_1_addr_reg_974;
wire   [0:0] and_ln74_fu_706_p2;
reg   [0:0] and_ln74_reg_980_pp0_iter1_reg;
reg   [0:0] and_ln74_reg_980_pp0_iter2_reg;
reg   [0:0] and_ln74_reg_980_pp0_iter3_reg;
reg   [0:0] and_ln74_reg_980_pp0_iter4_reg;
wire   [0:0] out_pkt_last_V_fu_717_p2;
reg   [0:0] out_pkt_last_V_reg_984;
reg   [0:0] out_pkt_last_V_reg_984_pp0_iter1_reg;
reg   [0:0] out_pkt_last_V_reg_984_pp0_iter2_reg;
reg   [0:0] out_pkt_last_V_reg_984_pp0_iter3_reg;
reg   [0:0] out_pkt_last_V_reg_984_pp0_iter4_reg;
reg   [0:0] out_pkt_last_V_reg_984_pp0_iter5_reg;
reg   [31:0] line_buf_0_load_reg_994;
reg   [31:0] line_buf_1_load_reg_999;
wire    ap_block_state6_pp0_stage3_iter0;
wire    ap_block_state15_pp0_stage3_iter1;
wire    ap_block_state24_pp0_stage3_iter2;
wire    ap_block_state33_pp0_stage3_iter3;
wire    ap_block_state42_pp0_stage3_iter4;
reg    ap_block_state51_pp0_stage3_iter5;
reg    ap_block_state51_io;
reg    ap_block_pp0_stage3_11001;
wire   [31:0] grp_fu_394_p2;
reg   [31:0] mul_reg_1010;
wire    ap_block_state7_pp0_stage4_iter0;
wire    ap_block_state16_pp0_stage4_iter1;
wire    ap_block_state25_pp0_stage4_iter2;
wire    ap_block_state34_pp0_stage4_iter3;
wire    ap_block_state43_pp0_stage4_iter4;
reg    ap_block_state52_pp0_stage4_iter5;
reg    ap_block_state52_io;
reg    ap_block_pp0_stage4_11001;
reg   [31:0] mul_0_1_reg_1020;
reg   [31:0] mul_0_2_reg_1025;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state8_pp0_stage5_iter0;
wire    ap_block_state17_pp0_stage5_iter1;
wire    ap_block_state26_pp0_stage5_iter2;
wire    ap_block_state35_pp0_stage5_iter3;
wire    ap_block_state44_pp0_stage5_iter4;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state9_pp0_stage6_iter0;
wire    ap_block_state18_pp0_stage6_iter1;
wire    ap_block_state27_pp0_stage6_iter2;
wire    ap_block_state36_pp0_stage6_iter3;
wire    ap_block_state45_pp0_stage6_iter4;
wire    ap_block_pp0_stage6_11001;
reg   [31:0] mul_1_reg_1035;
reg   [31:0] mul_1_reg_1035_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state10_pp0_stage7_iter0;
wire    ap_block_state19_pp0_stage7_iter1;
wire    ap_block_state28_pp0_stage7_iter2;
wire    ap_block_state37_pp0_stage7_iter3;
wire    ap_block_state46_pp0_stage7_iter4;
wire    ap_block_pp0_stage7_11001;
reg   [31:0] mul_1_1_reg_1045;
reg   [31:0] mul_1_1_reg_1045_pp0_iter1_reg;
wire   [31:0] grp_fu_358_p2;
reg   [31:0] acc_1_reg_1050;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state11_pp0_stage8_iter0;
wire    ap_block_state20_pp0_stage8_iter1;
wire    ap_block_state29_pp0_stage8_iter2;
wire    ap_block_state38_pp0_stage8_iter3;
wire    ap_block_state47_pp0_stage8_iter4;
wire    ap_block_pp0_stage8_11001;
reg   [31:0] mul_1_2_reg_1055;
reg   [31:0] mul_1_2_reg_1055_pp0_iter1_reg;
reg   [31:0] mul_1_2_reg_1055_pp0_iter2_reg;
reg   [31:0] mul_2_reg_1060;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] mul_2_reg_1060_pp0_iter2_reg;
reg   [31:0] mul_2_reg_1060_pp0_iter3_reg;
reg   [31:0] mul_2_1_reg_1065;
reg   [31:0] mul_2_1_reg_1065_pp0_iter2_reg;
reg   [31:0] mul_2_1_reg_1065_pp0_iter3_reg;
reg   [31:0] mul_2_1_reg_1065_pp0_iter4_reg;
reg   [31:0] mul_2_2_reg_1070;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state5_pp0_stage2_iter0;
wire    ap_block_state14_pp0_stage2_iter1;
wire    ap_block_state23_pp0_stage2_iter2;
wire    ap_block_state32_pp0_stage2_iter3;
wire    ap_block_state41_pp0_stage2_iter4;
wire    ap_block_state50_pp0_stage2_iter5;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] mul_2_2_reg_1070_pp0_iter2_reg;
reg   [31:0] mul_2_2_reg_1070_pp0_iter3_reg;
reg   [31:0] mul_2_2_reg_1070_pp0_iter4_reg;
reg   [31:0] acc_1_0_1_reg_1075;
reg   [31:0] acc_1_0_2_reg_1080;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] acc_1_1_reg_1085;
reg   [31:0] acc_1_1_1_reg_1090;
reg    ap_enable_reg_pp0_iter3;
reg   [31:0] acc_1_1_2_reg_1095;
reg   [31:0] acc_1_2_reg_1100;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] acc_1_2_1_reg_1105;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
wire    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage4_subdone;
reg   [31:0] ap_phi_mux_new_pixel_1_phi_fu_349_p4;
wire   [31:0] new_pixel_fu_759_p1;
wire   [31:0] ap_phi_reg_pp0_iter0_new_pixel_1_reg_345;
wire   [63:0] col_cast3_fu_656_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage6;
reg   [8:0] col_fu_190;
wire   [8:0] add_ln43_fu_723_p2;
reg   [30:0] row_fu_194;
wire   [30:0] select_ln41_4_fu_648_p3;
reg   [63:0] indvar_flatten_fu_198;
wire   [63:0] add_ln41_fu_558_p2;
reg    ap_block_pp0_stage3_01001;
reg   [31:0] grp_fu_358_p0;
reg   [31:0] grp_fu_358_p1;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage8;
reg   [31:0] grp_fu_394_p0;
reg   [31:0] grp_fu_394_p1;
wire   [31:0] bound_fu_487_p0;
wire   [63:0] cast_fu_484_p1;
wire   [31:0] bound_fu_487_p1;
wire   [29:0] tmp_fu_506_p4;
wire   [31:0] zext_ln41_1_fu_502_p1;
wire   [0:0] notrhs_fu_533_p2;
wire   [0:0] notlhs_fu_527_p2;
wire   [31:0] col_cast_fu_544_p1;
wire   [30:0] add_ln41_1_fu_564_p2;
wire   [0:0] icmp_ln43_fu_548_p2;
wire   [29:0] tmp_1_fu_582_p4;
wire   [0:0] icmp21_fu_592_p2;
wire   [0:0] icmp_fu_516_p2;
wire   [31:0] zext_ln41_fu_570_p1;
wire   [0:0] cmp69_mid1_fu_606_p2;
wire   [0:0] cmp69_fu_522_p2;
wire   [0:0] notrhs_mid1_fu_625_p2;
wire   [0:0] notlhs_mid1_fu_619_p2;
wire   [0:0] and_ln55_3_fu_630_p2;
wire   [0:0] and_ln55_fu_538_p2;
wire   [8:0] select_ln41_fu_574_p3;
wire   [31:0] select_ln41_4_cast_fu_644_p1;
wire   [0:0] icmp_ln56_fu_667_p2;
wire   [0:0] icmp_ln56_1_fu_673_p2;
wire   [0:0] and_ln55_2_fu_678_p2;
wire   [0:0] select_ln41_3_fu_636_p3;
wire   [7:0] tmp_3_fu_690_p4;
wire   [0:0] select_ln41_1_fu_598_p3;
wire   [0:0] icmp_ln74_fu_700_p2;
wire   [0:0] select_ln41_2_fu_611_p3;
wire   [0:0] icmp_ln92_fu_712_p2;
reg    grp_fu_358_ce;
reg    grp_fu_394_ce;
wire    ap_CS_fsm_state53;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state53_blk;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
reg    ap_condition_267;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 window_0_2 = 32'd0;
#0 window_1_2 = 32'd0;
#0 window_2_2 = 32'd0;
#0 window_0_1 = 32'd0;
#0 window_1_1 = 32'd0;
#0 window_2_1 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

conv2d_line_buf_0 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_0_address0),
    .ce0(line_buf_0_ce0),
    .q0(line_buf_0_q0),
    .address1(line_buf_0_addr_reg_968),
    .ce1(line_buf_0_ce1),
    .we1(line_buf_0_we1),
    .d1(line_buf_1_q0)
);

conv2d_line_buf_0 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_1_address0),
    .ce0(line_buf_1_ce0),
    .q0(line_buf_1_q0),
    .address1(line_buf_1_addr_reg_974),
    .ce1(line_buf_1_ce1),
    .we1(line_buf_1_we1),
    .d1(ap_phi_mux_new_pixel_1_phi_fu_349_p4)
);

conv2d_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .kernel_in_0_0(kernel_in_0_0),
    .kernel_in_0_1(kernel_in_0_1),
    .kernel_in_0_2(kernel_in_0_2),
    .kernel_in_1_0(kernel_in_1_0),
    .kernel_in_1_1(kernel_in_1_1),
    .kernel_in_1_2(kernel_in_1_2),
    .kernel_in_2_0(kernel_in_2_0),
    .kernel_in_2_1(kernel_in_2_1),
    .kernel_in_2_2(kernel_in_2_2),
    .img_size(img_size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_358_p0),
    .din1(grp_fu_358_p1),
    .ce(grp_fu_358_ce),
    .dout(grp_fu_358_p2)
);

conv2d_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_394_p0),
    .din1(grp_fu_394_p1),
    .ce(grp_fu_394_ce),
    .dout(grp_fu_394_p2)
);

conv2d_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U3(
    .din0(bound_fu_487_p0),
    .din1(bound_fu_487_p1),
    .dout(bound_fu_487_p2)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pkt_last_V_reg_984_pp0_iter5_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

conv2d_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone)))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_fu_190 <= 9'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_fu_190 <= add_ln43_fu_723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_198 <= 64'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_fu_198 <= add_ln41_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_267)) begin
        if (((1'd1 == and_ln55_1_reg_964) & (icmp_ln41_reg_955 == 1'd0))) begin
            new_pixel_1_reg_345 <= new_pixel_fu_759_p1;
        end else if ((1'b1 == 1'b1)) begin
            new_pixel_1_reg_345 <= ap_phi_reg_pp0_iter0_new_pixel_1_reg_345;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_fu_194 <= 31'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        row_fu_194 <= select_ln41_4_fu_648_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'd1 == and_ln74_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        acc_1_0_1_reg_1075 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln74_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_0_2_reg_1080 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'd1 == and_ln74_reg_980_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        acc_1_1_1_reg_1090 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'd1 == and_ln74_reg_980_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        acc_1_1_2_reg_1095 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'd1 == and_ln74_reg_980_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        acc_1_1_reg_1085 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'd1 == and_ln74_reg_980_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        acc_1_2_1_reg_1105 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'd1 == and_ln74_reg_980_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        acc_1_2_reg_1100 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        acc_1_reg_1050 <= grp_fu_358_p2;
        mul_1_2_reg_1055 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add13_reg_895 <= add13_fu_452_p2;
        bound_reg_950 <= bound_fu_487_p2;
        empty_28_reg_910 <= empty_28_fu_460_p1;
        empty_29_reg_915 <= empty_29_fu_463_p1;
        empty_30_reg_920 <= empty_30_fu_466_p1;
        empty_31_reg_925 <= empty_31_fu_469_p1;
        empty_32_reg_930 <= empty_32_fu_472_p1;
        empty_33_reg_935 <= empty_33_fu_475_p1;
        empty_34_reg_940 <= empty_34_fu_478_p1;
        empty_35_reg_945 <= empty_35_fu_481_p1;
        empty_reg_905 <= empty_fu_457_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln55_1_reg_964 <= and_ln55_1_fu_684_p2;
        and_ln74_reg_980 <= and_ln74_fu_706_p2;
        line_buf_0_addr_reg_968 <= col_cast3_fu_656_p1;
        line_buf_1_addr_reg_974 <= col_cast3_fu_656_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln74_reg_980_pp0_iter1_reg <= and_ln74_reg_980;
        and_ln74_reg_980_pp0_iter2_reg <= and_ln74_reg_980_pp0_iter1_reg;
        and_ln74_reg_980_pp0_iter3_reg <= and_ln74_reg_980_pp0_iter2_reg;
        and_ln74_reg_980_pp0_iter4_reg <= and_ln74_reg_980_pp0_iter3_reg;
        and_ln74_reg_980_pp0_iter5_reg <= and_ln74_reg_980_pp0_iter4_reg;
        icmp_ln41_reg_955 <= icmp_ln41_fu_553_p2;
        mul_2_reg_1060_pp0_iter2_reg <= mul_2_reg_1060;
        mul_2_reg_1060_pp0_iter3_reg <= mul_2_reg_1060_pp0_iter2_reg;
        out_pkt_last_V_reg_984_pp0_iter1_reg <= out_pkt_last_V_reg_984;
        out_pkt_last_V_reg_984_pp0_iter2_reg <= out_pkt_last_V_reg_984_pp0_iter1_reg;
        out_pkt_last_V_reg_984_pp0_iter3_reg <= out_pkt_last_V_reg_984_pp0_iter2_reg;
        out_pkt_last_V_reg_984_pp0_iter4_reg <= out_pkt_last_V_reg_984_pp0_iter3_reg;
        out_pkt_last_V_reg_984_pp0_iter5_reg <= out_pkt_last_V_reg_984_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        img_size_read_reg_839 <= img_size;
        kernel_in_0_0_read_reg_870 <= kernel_in_0_0;
        kernel_in_0_1_read_reg_875 <= kernel_in_0_1;
        kernel_in_0_2_read_reg_865 <= kernel_in_0_2;
        kernel_in_1_0_read_reg_885 <= kernel_in_1_0;
        kernel_in_1_1_read_reg_890 <= kernel_in_1_1;
        kernel_in_1_2_read_reg_880 <= kernel_in_1_2;
        kernel_in_2_0_read_reg_855 <= kernel_in_2_0;
        kernel_in_2_1_read_reg_860 <= kernel_in_2_1;
        kernel_in_2_2_read_reg_850 <= kernel_in_2_2;
        virt_size_reg_844 <= virt_size_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        line_buf_0_load_reg_994 <= line_buf_0_q0;
        line_buf_1_load_reg_999 <= line_buf_1_q0;
        window_0_1 <= window_0_2;
        window_0_2 <= line_buf_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        mul_0_1_reg_1020 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        mul_0_2_reg_1025 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        mul_1_1_reg_1045 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        mul_1_1_reg_1045_pp0_iter1_reg <= mul_1_1_reg_1045;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        mul_1_2_reg_1055_pp0_iter1_reg <= mul_1_2_reg_1055;
        mul_1_2_reg_1055_pp0_iter2_reg <= mul_1_2_reg_1055_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        mul_1_reg_1035 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        mul_1_reg_1035_pp0_iter1_reg <= mul_1_reg_1035;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'd1 == and_ln74_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mul_2_1_reg_1065 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mul_2_1_reg_1065_pp0_iter2_reg <= mul_2_1_reg_1065;
        mul_2_1_reg_1065_pp0_iter3_reg <= mul_2_1_reg_1065_pp0_iter2_reg;
        mul_2_1_reg_1065_pp0_iter4_reg <= mul_2_1_reg_1065_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'd1 == and_ln74_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        mul_2_2_reg_1070 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        mul_2_2_reg_1070_pp0_iter2_reg <= mul_2_2_reg_1070;
        mul_2_2_reg_1070_pp0_iter3_reg <= mul_2_2_reg_1070_pp0_iter2_reg;
        mul_2_2_reg_1070_pp0_iter4_reg <= mul_2_2_reg_1070_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln74_reg_980) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_2_reg_1060 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'd1 == and_ln74_reg_980) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        mul_reg_1010 <= grp_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln74_fu_706_p2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_pkt_last_V_reg_984 <= out_pkt_last_V_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        window_1_1 <= window_1_2;
        window_1_2 <= line_buf_1_load_reg_999;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        window_2_1 <= window_2_2;
        window_2_2 <= new_pixel_1_reg_345;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state53_blk = 1'b1;
    end else begin
        ap_ST_fsm_state53_blk = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_553_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln55_1_reg_964) & (icmp_ln41_reg_955 == 1'd0))) begin
        ap_phi_mux_new_pixel_1_phi_fu_349_p4 = new_pixel_fu_759_p1;
    end else begin
        ap_phi_mux_new_pixel_1_phi_fu_349_p4 = 32'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        grp_fu_358_ce = 1'b1;
    end else begin
        grp_fu_358_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8))) begin
        grp_fu_358_p0 = acc_1_2_1_reg_1105;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_358_p0 = acc_1_2_reg_1100;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7))) begin
        grp_fu_358_p0 = acc_1_1_2_reg_1095;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_358_p0 = acc_1_1_1_reg_1090;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6))) begin
        grp_fu_358_p0 = acc_1_1_reg_1085;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_358_p0 = acc_1_0_2_reg_1080;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
        grp_fu_358_p0 = acc_1_0_1_reg_1075;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_358_p0 = acc_1_reg_1050;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_358_p0 = mul_reg_1010;
    end else begin
        grp_fu_358_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8))) begin
        grp_fu_358_p1 = mul_2_2_reg_1070_pp0_iter4_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_358_p1 = mul_2_1_reg_1065_pp0_iter4_reg;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7))) begin
        grp_fu_358_p1 = mul_2_reg_1060_pp0_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_358_p1 = mul_1_2_reg_1055_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6))) begin
        grp_fu_358_p1 = mul_1_1_reg_1045_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_358_p1 = mul_1_reg_1035_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
        grp_fu_358_p1 = mul_0_2_reg_1025;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_358_p1 = mul_0_1_reg_1020;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_358_p1 = 32'd0;
    end else begin
        grp_fu_358_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        grp_fu_394_ce = 1'b1;
    end else begin
        grp_fu_394_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8))) begin
            grp_fu_394_p0 = new_pixel_1_reg_345;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7))) begin
            grp_fu_394_p0 = window_2_2;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6))) begin
            grp_fu_394_p0 = window_2_1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
            grp_fu_394_p0 = line_buf_1_load_reg_999;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4))) begin
            grp_fu_394_p0 = window_1_2;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
            grp_fu_394_p0 = window_1_1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
            grp_fu_394_p0 = line_buf_0_load_reg_994;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_394_p0 = window_0_2;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_394_p0 = window_0_1;
        end else begin
            grp_fu_394_p0 = 'bx;
        end
    end else begin
        grp_fu_394_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8))) begin
            grp_fu_394_p1 = empty_35_reg_945;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7))) begin
            grp_fu_394_p1 = empty_34_reg_940;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6))) begin
            grp_fu_394_p1 = empty_33_reg_935;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
            grp_fu_394_p1 = empty_32_reg_930;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4))) begin
            grp_fu_394_p1 = empty_31_reg_925;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
            grp_fu_394_p1 = empty_30_reg_920;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
            grp_fu_394_p1 = empty_29_reg_915;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_394_p1 = empty_28_reg_910;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_394_p1 = empty_reg_905;
        end else begin
            grp_fu_394_p1 = 'bx;
        end
    end else begin
        grp_fu_394_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'd1 == and_ln55_1_reg_964) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op185_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_0_ce0 = 1'b1;
    end else begin
        line_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        line_buf_0_ce1 = 1'b1;
    end else begin
        line_buf_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        line_buf_0_we1 = 1'b1;
    end else begin
        line_buf_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_1_ce0 = 1'b1;
    end else begin
        line_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        line_buf_1_ce1 = 1'b1;
    end else begin
        line_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln41_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        line_buf_1_we1 = 1'b1;
    end else begin
        line_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg) & (1'b0 == ap_block_pp0_stage4)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg) & (1'b0 == ap_block_pp0_stage3)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln41_fu_553_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln41_fu_553_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone)) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else if (((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_state53 : begin
            if (((1'b1 == ap_CS_fsm_state53) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add13_fu_452_p2 = (img_size_read_reg_839 + 32'd1);

assign add_ln41_1_fu_564_p2 = (row_fu_194 + 31'd1);

assign add_ln41_fu_558_p2 = (indvar_flatten_fu_198 + 64'd1);

assign add_ln43_fu_723_p2 = (select_ln41_fu_574_p3 + 9'd1);

assign and_ln55_1_fu_684_p2 = (select_ln41_3_fu_636_p3 & and_ln55_2_fu_678_p2);

assign and_ln55_2_fu_678_p2 = (icmp_ln56_fu_667_p2 & icmp_ln56_1_fu_673_p2);

assign and_ln55_3_fu_630_p2 = (notrhs_mid1_fu_625_p2 & notlhs_mid1_fu_619_p2);

assign and_ln55_fu_538_p2 = (notrhs_fu_533_p2 & notlhs_fu_527_p2);

assign and_ln74_fu_706_p2 = (select_ln41_1_fu_598_p3 & icmp_ln74_fu_700_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd11];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op185_read_state4 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op185_read_state4 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state51_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state51_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg))));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state52_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg))));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state52_io) | ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg))));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage8_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage8_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage6_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage7_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage8_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage5_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage6_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage7_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage8_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = ((ap_predicate_op185_read_state4 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0));
end

assign ap_block_state50_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state51_io = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg));
end

always @ (*) begin
    ap_block_state51_pp0_stage3_iter5 = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg));
end

always @ (*) begin
    ap_block_state52_io = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg));
end

always @ (*) begin
    ap_block_state52_pp0_stage4_iter5 = ((out_stream_TREADY_int_regslice == 1'b0) & (1'd1 == and_ln74_reg_980_pp0_iter5_reg));
end

assign ap_block_state5_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_267 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_new_pixel_1_reg_345 = 32'd0;

always @ (*) begin
    ap_predicate_op185_read_state4 = ((1'd1 == and_ln55_1_reg_964) & (icmp_ln41_reg_955 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_487_p0 = cast_fu_484_p1;

assign bound_fu_487_p1 = cast_fu_484_p1;

assign cast_fu_484_p1 = virt_size_reg_844;

assign cmp69_fu_522_p2 = ((zext_ln41_1_fu_502_p1 == add13_reg_895) ? 1'b1 : 1'b0);

assign cmp69_mid1_fu_606_p2 = ((zext_ln41_fu_570_p1 == add13_reg_895) ? 1'b1 : 1'b0);

assign col_cast3_fu_656_p1 = select_ln41_fu_574_p3;

assign col_cast_fu_544_p1 = col_fu_190;

assign empty_28_fu_460_p1 = kernel_in_2_1_read_reg_860;

assign empty_29_fu_463_p1 = kernel_in_2_0_read_reg_855;

assign empty_30_fu_466_p1 = kernel_in_1_2_read_reg_880;

assign empty_31_fu_469_p1 = kernel_in_1_1_read_reg_890;

assign empty_32_fu_472_p1 = kernel_in_1_0_read_reg_885;

assign empty_33_fu_475_p1 = kernel_in_0_2_read_reg_865;

assign empty_34_fu_478_p1 = kernel_in_0_1_read_reg_875;

assign empty_35_fu_481_p1 = kernel_in_0_0_read_reg_870;

assign empty_fu_457_p1 = kernel_in_2_2_read_reg_850;

assign icmp21_fu_592_p2 = ((tmp_1_fu_582_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_fu_516_p2 = ((tmp_fu_506_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_553_p2 = ((indvar_flatten_fu_198 == bound_reg_950) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_548_p2 = ((col_cast_fu_544_p1 == virt_size_reg_844) ? 1'b1 : 1'b0);

assign icmp_ln56_1_fu_673_p2 = (($signed(select_ln41_4_cast_fu_644_p1) < $signed(add13_reg_895)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_667_p2 = ((select_ln41_fu_574_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_700_p2 = ((tmp_3_fu_690_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_712_p2 = ((select_ln41_4_cast_fu_644_p1 == add13_reg_895) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign line_buf_0_address0 = col_cast3_fu_656_p1;

assign line_buf_1_address0 = col_cast3_fu_656_p1;

assign new_pixel_fu_759_p1 = in_stream_TDATA_int_regslice;

assign notlhs_fu_527_p2 = ((row_fu_194 != 31'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_619_p2 = ((add_ln41_1_fu_564_p2 != 31'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_533_p2 = (($signed(zext_ln41_1_fu_502_p1) < $signed(add13_reg_895)) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_625_p2 = (($signed(zext_ln41_fu_570_p1) < $signed(add13_reg_895)) ? 1'b1 : 1'b0);

assign out_pkt_last_V_fu_717_p2 = (select_ln41_2_fu_611_p3 & icmp_ln92_fu_712_p2);

assign out_stream_TDATA_int_regslice = grp_fu_358_p2;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign select_ln41_1_fu_598_p3 = ((icmp_ln43_fu_548_p2[0:0] == 1'b1) ? icmp21_fu_592_p2 : icmp_fu_516_p2);

assign select_ln41_2_fu_611_p3 = ((icmp_ln43_fu_548_p2[0:0] == 1'b1) ? cmp69_mid1_fu_606_p2 : cmp69_fu_522_p2);

assign select_ln41_3_fu_636_p3 = ((icmp_ln43_fu_548_p2[0:0] == 1'b1) ? and_ln55_3_fu_630_p2 : and_ln55_fu_538_p2);

assign select_ln41_4_cast_fu_644_p1 = select_ln41_fu_574_p3;

assign select_ln41_4_fu_648_p3 = ((icmp_ln43_fu_548_p2[0:0] == 1'b1) ? add_ln41_1_fu_564_p2 : row_fu_194);

assign select_ln41_fu_574_p3 = ((icmp_ln43_fu_548_p2[0:0] == 1'b1) ? 9'd0 : col_fu_190);

assign tmp_1_fu_582_p4 = {{add_ln41_1_fu_564_p2[30:1]}};

assign tmp_3_fu_690_p4 = {{select_ln41_fu_574_p3[8:1]}};

assign tmp_fu_506_p4 = {{row_fu_194[30:1]}};

assign virt_size_fu_431_p2 = (img_size + 32'd2);

assign zext_ln41_1_fu_502_p1 = row_fu_194;

assign zext_ln41_fu_570_p1 = add_ln41_1_fu_564_p2;

endmodule //conv2d
